---
author: 'KINIF Pierrick'
date: 'May 2018'
institution: 'University of Namur'
division: 'Faculty of Economics, Social Sciences and Business Administration'
advisor: 'Professor Bereau Sophie'
altadvisor: 'Professor Jean-Yves Koudou Gnabo'
# Delete line 6 if you only have one advisor
department: 'The Center for Research in Finance and Management (CeReFiM)'
degree: "in Business Management and Administration, Finance specialisation"
title: "Master's Thesis"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  thesisdown::thesis_pdf: default
#  thesisdown::thesis_gitbook: default
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content here or
# use code similar to line 20 for the files.  If you are producing in a different
# format than PDF, you can delete or ignore lines 20-31 in this YAML header.
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the |.
acknowledgements: |
  I want to thank a few people.
dedication: |
  You can have a dedication here if you wish. 
preface: |
  This is an example of a thesis setup to use the reed thesis document class
  (for LaTeX) and the R bookdown package, in general.
bibliography: bib/thesis.bib
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
lot: true
lof: true
space_between_paragraphs: true
fontsize: 12pt
linestretch: 1.5
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(thesisdown)
```

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for
PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd
and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->


# Introduction {-}

Over the past decades, humanity is progressively becoming aware of the finiteness of earth’s resources and its impact on the current global warming. On the one hand, @HoughtonClimateChange19951996 anticipated in their first report an average global warming between +1° and +3.5° C until 2100 relative to the temperature of 1990. They also warned that an increase of temperatures superior to +2° C could have some harsh climatic repercussions. On the other hand the Kyoto Protocol had been written in 1997, enforced in 2005 and led to the first Global Agreement on global warming during the Paris Conference in 2015. Those different solutions implemented over the past decades did not have any significant impacts on the fight against global warming. Greenhouse Gas Emissions (GGE) have still increased considerably across years. Although the environmental consciousness-raising had already gained ground, according to @JeanJouzel2017 human being have to act now if he we want to have a chance to reduce effects of climate change. 

For the last several decades, companies have been more and more considered as entities responsible for stewardship of the natural environment [@MajumdarRulesDiscretionProductivity2001; @PrzychodzenRelationshipsecoinnovationfinancial2015]. Ecosystem degradation and resources depletion engender a threat to firm’s longevity [@Dowell2000], and as a reaction, firms have to pro-actively adopt an environmental strategy [@HartNaturalResourceBasedViewFirm1995]. In his speech at Lloyds of London 2015, Mark Carney, Governor of the Bank of England and Chair of the Financial Stability Board (FSB), identified climate change as one of the most material threats to financial stability [@Elliott2015]. To this end, companies facing higher risks associated to climate change are ones subject to greater incentives to develop green strategies [@HoffmanClimateChangeStrategy2005]. However, both economic benefits and strategic opportunities deriving from sustainable development are usually underestimated by managers and still too many companies do not feel concerned about global warming [@Berchicci11PostcardsEdge2007; @HartNaturalResourceBasedViewFirm1995]. Moreover, according to @Scarpellinieconomicfinanceinterface2016, green projects are not common in companies of many countries because of significant barriers and a negligible culture of excluding sustainable development from an organization’s strategy. If we consider that people’s actions reflect a variable mix of altruistic motivation, material self-interest, and social or self-image concerns [@BenabouIncentivesProsocialBehavior2006], demonstrating that green development is a significant interest for firms could be a serious step forward in the fight against global warming.

**To be continued...**

<!--  Continue with somethink like this :

From Delmas et al 2015 :

In this study, the impacts of corporate green practices on CFP are examined following the sustainable-value framework proposed by Hart and
Milstein (2003). Using a panel of 3490 publicly-traded firms from 58 countries for the period 2002e2014, this study explores whether internal and external green practices are able, individually and in combination, to improve CFP at company level. Corporate green practices’ effects on both market-based and accountingbased measures of CFP are examined.

The rest of the paper is organized as follows: the next section
provides an overview of the main findings emerging from the literature related to the hypotheses of the study. After that, the dataset and the estimation methodology are described. Next, the results are presented and discussed. The last section discusses the main contributions to the literature and avenues for future research.

-->


