# Discussion and Conclusion 

Using a panel data of 393 US publicly traded companies for the period 2012-2014, this study first investigates the impact of process-based CEP on outcome-based CEP. Then, it explores whether the combined effect of process-based and outcome-based CEP influences CFP. Finally, it observes the time influence (i.e. short-term vs long-term) on the relationship.

This study shows that process-based CEP positively influences outcome-based CEP. More precisely, it stresses that (i) companies which link the remuneration of any member of a company’s senior executive team with the achievement of environmental performance targets, have a better WatP and WastP. Then, (ii) the fact of having a sustainability committee on the board of directors level increases the CaP, WatP and, WastP. Finally, (iii) companies having their latest reported environmental metrics audited by a third party have a higher CaP, WatP and, WastP.

The results support findings of previous studies that demonstrated the implementation of environmental management measures allows companies to significantly increase their environmental performance [@Melnyk2003; @Xie2007; @Li2017; @Chencrosscountrycomparisongreen2018]. One possible explanation for this relationship could be the employees' engagement. The latter would allow individuals to gain awareness of the environmental footprint of their companies, making them strongly involved in the process of change towards greener companies. Moreover, companies having their latest reported environmental metrics audited by a third party could be driven by the willingness of real improvements. Engagement in process-based CEP could also make companies be more concerned about the whole process and not only on its outputs.

Furthermore, this study provides evidence that both process and outcome-based CEP have a positive impact on CFP. This relationship is always positive, no matter the time horizon, and is stronger with a long-term perspective than a short-term perspective. Regarding the process-based CEP, the empirical results show that (iv) companies which link the remuneration of any member of a company’s senior executive team with the achievement of environmental performance targets are characterized by both a higher short-term and long-term CFP. Then, (v) the fact of having a sustainability committee on the board of directors level increases the short-term CFP. Lastly, (vi) companies having their latest reported environmental metrics audited by a third party have a higher long-term CFP. Regarding outcome-based CEP variables, results demonstrate that (vii) companies which have a higher CaP and CatP have respectively a higher short-term and long-term CFP. 

These results corroborate recent meta-analyses that claimed positive influence between CEP and CFP [@Orlitzky2003; @Wu2006; @Albertini2013; @Dixon-Fowler2013; @EndrikatMakingsenseconflicting2014; @Ludecadedebatenexus2014; @WangMetaAnalyticReviewCorporate2016; @Busch2018]. Furthermore, findings support the general consensus that accounting-based measures are characterized by a stronger relation to CEP than market-based indicators [@Orlitzky2003; @Wu2006; @Albertini2013; @Ludecadedebatenexus2014; @Busch2018]. 

This study also proves that @Ambec2008 were right in affirming that expenses incurred to reduce pollution can be offset by gains made elsewhere. The positive influence of CEP on CFP could be partly explained by the increasing awareness of citizens on environmental degradation who impact the demand for green products and services [@Leonidou2013; @Kotler2011]. Thus, results of this study provide a genuine economic justification to the new paradigm which mediates business and respect of the environment. Lastly, this study emphasizes strong incentives for companies to invest in environmental strategies. 

The contributions of this empirical study are twofold. First, I provide an initial answer to the research call of @EndrikatMakingsenseconflicting2014 who highlighted the need for a better understanding of
the multidimensionality of both CEP and CFP constructs. Second, I give a first overview of the call of @Griffin1997 and @Busch2018 who called for studies that look at the CEP-CFP relationship over time.

This study has some limitation and consequently, highlights potential future research. First, the time horizon is relatively small (i.e. 3 years) and may consequently not totally capture how changes in CEP affect changes in CFP. Furthermore, it implies that I could not consider a lagged variables in equation \ref{CEP}. Therefore, the econometric model could suffer from a simultaneity bias. One feasible approach for future research is to expect for latter NGR and reproduce this study by considering a larger time horizon. To deal with the endogeneity concern in equation \ref{CEP}, a future approach could also consider adding an instrumental variable to uncover the causal effect of process-based CEP on outcome-based CEP.

Second, market-based indicators are imperfect proxies for long-term CFP. Considering Tobin's Q as a measure of long-term performance gives too much credit to the Efficient Market Hypothesis. As claimed by @Malkiel2003, the market cannot be perfectly efficient, or there would be no incentive for professionals to uncover the information that gets so quickly reflected in market prices. Future research should investigate a better approach to measure long-term CFP. 

Third, CEP is a large construct and a lot of methodologies have been developed to assess this concept. Due to data limitation, no robustness test considering alternative CEP data sources has been performed. However, reproduce this study by considering other CEP data source could potentially provide different results. Indeed, @Delmas2010 demonstrated that the rating of companies varies significantly according to whether the screening methodology is based on toxic releases and regulatory compliance or on the quality of environmental policy and disclosure. Future research could reproduce this study in taking into account other CEP data sources (e.g. Asset4 ESG data from Thomson Reuters) and compare the results with the ones of this study. Future research should also refine current methodologies to measure and communicate firm’s environmental performance.
