# Discussion

Findings of this study show that process-based CEP positively influence outcome-based CEP. Then, it provides evidence that both process and outcome-based CEP have a positive impact on CFP.  This relationship is always positive, no matter the time horizon, and is stronger with a long-term perspective than a short-term perspective. Hence, results highlights that companies with better environmental performance have also better short-term and long-term financial performance.

These results support findings of @Xie2007, @Li2017 and @Chencrosscountrycomparisongreen2018 confirming that implementation of environmental management measures allows companies to significantly increase their performance in carbon productivity, water productivity, and waste productivity which in turn will reduce their environmental impact. These results also corroborate recent meta-analyses that claim positive influence between CEP and CFP [@Orlitzky2003; @Wu2006; @Albertini2013; @Dixon-Fowler2013; @EndrikatMakingsenseconflicting2014; @Ludecadedebatenexus2014; @WangMetaAnalyticReviewCorporate2016; @Busch2018]. Furthermore, findings support the general consensus that accounting-based measures are characterized by a stronger relation to CEP than market-based indicators [@Orlitzky2003; @Wu2006; @Albertini2013; @Ludecadedebatenexus2014; @Busch2018]. 

This study proves that @Ambec2008 were right in affirming that expenses incurred to reduce pollution can be offset by gains made elsewhere. The positive influence of CEP on CFP could be partly explained by the increasing awareness of citizens on environmental degradation who impact the demand for green products and services [@Leonidou2013; @Kotler2011]. Thus, results of this study provide a genuine economic justification to the new paradigm of doing business and also emphasizes strong incentives for companies to invest in environmental strategies. 

This study has some limitation and consequently, highlights potential future researchs. First, the time horizon of this study is relatively small (i.e. 3 years) and may consequently not totally capture how the changes in CEP affect the changes in CFP. One feasible approach for future research could be to expect for the latter Newsweek Green Rankings and reproduce this study in considering a larger time horizon. 

Second, market-based indicators are imperfect proxies for long-term CFP. Considering Tobin's Q as a measure of long-term performance gives too much credit to the Efficient Market Hypothesis. As claimed by [@Malkiel2003], the market cannot be perfectly efficient, or there would be no incentive for professionals to uncover the information that gets so quickly reflected in market prices. Future research should investigate a better approach to measure long-term CFP. 

Third, due to data limitation, I could not carry out a robustness test which considers different data source as a proxy for CEP. Future research could reproduce this study in taking into account another database that approachs CEP (e.g. Asset4 ESG data from Thomson Reuters) and compare the results with the ones of this study.

Finally, the large construct of CEP implies that a lot of methodologies have been developped in order to assess the corporate environmental performance. @Delmas2010 demonstrated that,  the rating of companies varies significantly according to whether the screening methodology is based on toxic releases and regulatory compliance or on the quality of environmental policy and disclosure. Hence, reproduce this study in considering another CEP proxies could potentially provides different results. Hence, future research should refine current methodologies to measure and communicate firm’s environmental performance.

