

# Introduction 

Over the past decades, humanity has progressively become aware of the finiteness of earth’s resources and its impact on the current global warming. @Meadows1972 (p23) concludes that  *"if the present growth trends in world population, industrialization, pollution, food production, resource depletion continue unchanged, the limits to growth on this planet will be reached sometime within the next one hundred years"*. @HoughtonClimateChange19951996 also claim that *"in the absence of mitigation policies, greenhouse gas emissions will continue to rise during the next century"* (p9). This will *"increase the global mean surface air temperature relative to 1990 of about 2°C by 2100...leading to harsh climatic repercussions"* (p23). 

Over the last 30 years, these predictions have come true. For the first time in 400 000 years, atmospheric carbon dioxide crossed, in 1950, the level of 300 Parts Per Million\footnote{A concentration of 300 PPM means that for every million air particles, 300 of them are carbon dioxide molecules, namely a carbon concentration of 0.03\%.} (i.e. PPM) [@PieterTans2018]. According to the NOAA's Annual Greenhouse Gas Index, the atmospheric abundance of \(CO_{2}\) increased by an average of 1.80 PPM per year from 1979 to 2016 [@Butler2016]. In May 2018, the global level of carbon dioxide has reached 410 PPM [@PieterTans2018]. This increase led to direct effects.

Since the \(19^{th}\) century, the average temperature of the planet increased (+1.1°C). Most of the warming occurred in the past 35 years, with 16 of the 17 warmest years on record occurring since 2001 [@Hansen2010; @GistempTeam2018]. Data from NASA's Gravity Recovery and Climate Experiment show Greenland lost 150 to 250 cubic kilometers of ice per year between 2002 and 2006, while Antarctica lost about 152 cubic kilometers of ice between 2002 and 2005 [@GistempTeam2018]. @Church2006 showed that, in the last century, the global sea level rose (+8 inches). Due to a high carbon dioxide absorption level [@Sabine2004], the acidity of surface ocean waters also increased (+30%) [@NOAAsPacificMarineEnvironmentalLaboratory] leading, *inter alia*, to harsh repercussions to corals.

Ecosystem degradation and resources depletion engender a threat to firm’s longevity [@Dowell2000]. Mark Carney, Governor of the Bank of England and Chair of the Financial Stability Board, identifies climate change as one of the most material threats to financial stability [@Elliott2015]. The @BusinessandSustainableDevelopmentCommission2017 (p12) report states: *"... businesses need to pursue social and environmental sustainability as avidly as they pursue market share and shareholder value... If they don’t, the costs and uncertainty of unsustainable development could swell until there is no viable world in which to do business."* In other words, adopting environmental strategies ensure companies' competitiveness and survival in the near future.

@Testa2018 show that, due to institutional pressure or the influence of stakeholders, a majority of companies have integrated, either substantially or symbolically (i.e. greenwashing), proactive environmental practices. However, according to @Scarpellinieconomicfinanceinterface2016, green projects are still not common in companies of many countries because of significant barriers and a negligible culture of excluding sustainable development from an organization’s strategy. 

People’s actions reflect a variable mix of altruistic motivation, material self-interest, and social or self-image concerns [@BenabouIncentivesProsocialBehavior2006]. Hence, for more than 40 years, scholars have analyzed the Corporate Environmental Performance (i.e. CEP) and Corporate Financial Performance (i.e. CFP) nexus to provide evidence that it does pay to be green and to convince companies to incorporate environmental sustainability into their core values and strategies [@Ludecadedebatenexus2014]. 

The International Organization for Standardization [@ISO2013] defines CEP as *“measurable results of an organization’s management of its environmental aspects”*. The CFP construct assesses the outcomes of business strategy [@Bansal2014] and is a fundamental indicator of organizational performance and long-term survival of an organization [@Hamann2013]. 

The relationship between CEP and CFP is broadly discussed in the literature and is characterized by inconsistent empirical findings [@EndrikatMakingsenseconflicting2014]. Two major opposite trends have emerged. Some scholars [@ManriqueAnalyzingEffectCorporate2017; @MiroshnychenkoGreenpracticesfinancial2017; @Chencrosscountrycomparisongreen2018] provide evidence of a positive link between CEP and CFP while others [@Busch2011a; @Fernando2010; @Fisher-Vanden2008] demonstrate a negative relationship. This inconclusiveness may come from the multidimensionality of both focal constructs [@Griffin1997; @EndrikatMakingsenseconflicting2014; @Albertini2013]. Indeed, commonly shared understanding or conceptualization of CEP and CFP has not been established so far [@Etzion2007; @Hamann2013]. 

Indeed, @EndrikatMakingsenseconflicting2014 argue that a two-group classification of CEP can be deduced from the literature. (i) Process-based CEP which refers to *"a strategic level and focuses on managerial principles and processes such as environmental objectives, environmental policies, or environmental management structures"*. (ii) Outcome-based CEP which reflects *"the observable and quantifiable results of these efforts [@Delmas2011a] and refers to measures such as the number of released pollutants or the ratio of recycled waste to total waste"*. 

Regarding CFP, scholars have adopted three broad subdivisions: market-based (i.e. investor returns), accounting-based (i.e. accounting returns), and perceptual (i.e. survey) measures [@Ludecadedebatenexus2014]. Furthermore, the multidimensionality of CFP includes a wide array of estimations that may capture a firm’s ability to generate value in the short-term and company’s future growth prospects assessed by the external stakeholders [@Opler1994; @MiroshnychenkoGreenpracticesfinancial2017].

@EndrikatMakingsenseconflicting2014 highlight the need for a better understanding of the multidimensionality of both CEP and CFP constructs. Furthermore, @King2002 suggest that *“When does it pay to be green?”* may be a more important question than *“Does it pay to be green?”*. @Griffin1997 is the first to call for studies that look at the CEP-CFP relationship over time. To that extent, @Busch2018 demonstrate that, at a meta-research level, evidence of a time dependency on the CEP-CFP link are not significant and that the call of @Griffin1997 remains unanswered. Therefore, using a panel data of 393 US publicly traded companies for the period 2012-2014, this study first investigates the impact of process-based CEP on outcome-based CEP. Then, it explores whether the combined effect of process-based and outcome-based CEP influences CFP. Finally, it observes the time influence (i.e. short-term vs long-term) on the relationship.

This study provides evidence that process-based CEP positively influences outcome-based CEP and supports the idea that it does pay to be green. More precisely, it demonstrates that both process and outcome-based CEP have a positive impact on CFP, no matter the time horizon, and is stronger with a long-term perspective than a short-term perspective. This study emphasizes strong incentives for companies to invest in environmental strategies.

The rest of the paper is organized as follows: the next section reviews the literature regarding the CEP-CFP nexus. Then, I describe the database and methodology. Next, the results are presented. Finally, I discuss the main contributions to the literature and highlight potential future research.




