The following `R` script is the one used to produce the section : *"[Sensitivity Analysis]"*.

### Packages Loading {-}

```{r message = FALSE, size = 'smallsize', error = FALSE, warning = FALSE, results = 'asis', tidy = TRUE, comment = FALSE, tidy.opts=list(blank=FALSE, width.cutoff=55), eval = FALSE}


# Packages loading 
rm(list=ls()) #Removes all items in the R environment
if (!require("plm")) install.packages("plm")
library(plm) 
if (!require("dplyr")) install.packages("dplyr")
library(dplyr) 
if (!require("data.table")) install.packages("data.table")
library(data.table)
if (!require("stargazer")) install.packages("stargazer")
library(stargazer)

```

### The Impact of CEP on CFP {-}

```{r message = FALSE, size = 'smallsize', error = FALSE, warning = FALSE, results = 'asis', tidy = TRUE, comment = FALSE, tidy.opts=list(blank=FALSE, width.cutoff=55), eval = FALSE}

# I have already removed outliers from both models (i.e. Roa and TobinsQ) via the file = "Analysis/MakeFile_RemoveOutliers_Lag2.rmd". 
# Consequently I just need to load folowing databases.
p <- "Analysis/DataBase/DataSynchronization/NoOutliersLag2/Roa.csv"
RoaNoOut <- read.csv(file = p, header = TRUE, stringsAsFactors = FALSE)
p <- "Analysis/DataBase/DataSynchronization/NoOutliersLag2/TobinsQ.csv"
TobinNoOut <- read.csv(file = p, header = TRUE, stringsAsFactors = FALSE)

# I change names
RoaNoOut <- RoaNoOut %>% setnames(old = c("Roa", "FinancialLeverage","CarbonProductivity", "WaterProductivity", "WasteProductivity", "SustainabilityPayLink", "SustainableThemedCommitment", "AuditScore"), new = c("ROA", "Leverage", "CaP", "WaP", "WastP", "SPL", "STC", "AS"))
TobinNoOut <- TobinNoOut %>% setnames(old = c("Roa", "FinancialLeverage","CarbonProductivity", "WaterProductivity", "WasteProductivity", "SustainabilityPayLink", "SustainableThemedCommitment", "AuditScore"), new = c("ROA", "Leverage", "CaP", "WaP", "WastP", "SPL", "STC", "AS"))

# I make both df a plm dataframe
RoaNoOut <- RoaNoOut %>% pdata.frame(index = c("CompaniesIndex", "YearIndex"))
TobinNoOut <- TobinNoOut %>% pdata.frame(index = c("CompaniesIndex", "YearIndex"))

# I test for Random Effect Model using the Lagrange Multiplier Tests for Panel Models. 

# Pooling Model
RoaPooling <- plm(ROA ~ SPL + STC + AS + CaP + WaP + WastP + FirmSize + Leverage + Growth + Industry, data = RoaNoOut, model="pooling")
TobinPooling <- plm(TobinsQ ~ SPL + STC + AS + CaP + WaP + WastP + FirmSize + Leverage + Growth + Industry, data = TobinNoOut, model="pooling")


# Plmtest
PlmtestRoa <-as.numeric(round(plmtest(RoaPooling, effect = "time", type = "bp")$p.value, digits = 3))
PlmtestTobin <-as.numeric(round(plmtest(TobinPooling, effect = "time", type = "bp")$p.value, digits = 3))

# Improve p-value understanding
PlmtestRoa<-ifelse(PlmtestRoa<0.01, paste(PlmtestRoa,"***",sep = ""),
	ifelse(PlmtestRoa<0.05,paste(PlmtestRoa,"**",sep = ""),
	ifelse(PlmtestRoa<0.1,paste(PlmtestRoa,"*",sep = ""),PlmtestRoa)))
PlmtestTobin<-ifelse(PlmtestTobin<0.01, paste(PlmtestTobin,"***",sep = ""),
	ifelse(PlmtestTobin<0.05,paste(PlmtestTobin,"**",sep = ""),
	ifelse(PlmtestTobin<0.1,paste(PlmtestTobin,"*",sep = ""),PlmtestTobin)))

# I test for Fixed Effect Model using pFtest which is a test of individual and/or time effects based on the comparison of the within and the pooling model.

## Within Model with time effect

RoaWithin <- plm(ROA ~ SPL + STC + AS + CaP + WaP + WastP + FirmSize + Leverage + Growth + Industry, data = RoaNoOut, model="within", effect = "time")
TobinWithin <- plm(TobinsQ ~ SPL + STC + AS + CaP + WaP + WastP + FirmSize + Leverage + Growth + Industry, data = TobinNoOut, model = "within", effect = "time")

# pFtest

pFtestRoa <- round(pFtest(RoaWithin, 
                          RoaPooling)$p.value, digits = 3)
pFtestTobin <- round(pFtest(TobinWithin, 
                            TobinPooling)$p.value, digits = 3)

# Improve p-value understanding
pFtestRoa<-ifelse(pFtestRoa<0.01, paste(pFtestRoa, "***",sep = ""),
	ifelse(pFtestRoa<0.05,paste(pFtestRoa,"**",sep = ""),
	ifelse(pFtestRoa<0.1,paste(pFtestRoa,"*",sep = ""),pFtestRoa)))
pFtestTobin<-ifelse(pFtestTobin<0.01, paste(pFtestTobin,"***",sep = ""),
	ifelse(pFtestTobin<0.05,paste(pFtestTobin,"**",sep = ""),
	ifelse(pFtestTobin<0.1,paste(pFtestTobin,"*",sep = ""),pFtestTobin)))

# Based on the results of the tests, the two models need to be estimated with the pooling ols estimations (i.e. model = "pooling" in plm). Let's consolidate into a nice stargazer table
titre <- "The impact of process and outcome-based CEP on CFP (lag = 2)"
stargazer(TobinPooling, 
          RoaPooling, 
          title = titre, 
          label = "Lag2", 
          header = FALSE, 
          single.row = TRUE,
          type = "latex", 
          align = FALSE, 
          model.numbers = FALSE, 
          table.placement = "!", 
          add.lines = list(c("BPLM test (pvalue)", PlmtestTobin, PlmtestRoa),
                         c("F test (pvalue)", pFtestTobin ,pFtestRoa)))
```
### Green Score as an Alternative {-}

```{r message = FALSE, size = 'smallsize', error = FALSE, warning = FALSE, results = 'asis', tidy = TRUE, comment = FALSE, tidy.opts=list(blank=FALSE, width.cutoff=55), eval = FALSE}


# I have already removed outliers from both models (i.e. Roa and TobinsQ) via the file = "Analysis/MakeFile_RemoveOutliers_Lag1.rmd". 
# Consequently I just need to load folowing databases.
p <- "Analysis/DataBase/DataSynchronization/NoOutliersLag1/GreenScore/Roa.csv"
RoaNoOut <- read.csv(file = p, header = TRUE, stringsAsFactors = FALSE)
p <- "Analysis/DataBase/DataSynchronization/NoOutliersLag1/GreenScore/TobinsQ.csv"
TobinNoOut <- read.csv(file = p, header = TRUE, stringsAsFactors = FALSE)

# I change names
RoaNoOut <- RoaNoOut %>% setnames(old = c("GreenScore", "FinancialLeverage", "Roa"), new = c("GS", "Leverage", "ROA"))
TobinNoOut <- TobinNoOut %>% setnames(old = c("GreenScore", "FinancialLeverage", "Roa"), new = c("GS", "Leverage", "ROA"))


# I make both df a plm dataframe
RoaNoOut <- RoaNoOut %>% pdata.frame(index = c("CompaniesIndex", "YearIndex"))
TobinNoOut <- TobinNoOut %>% pdata.frame(index = c("CompaniesIndex", "YearIndex"))

# I test for Random Effect Model using the Lagrange Multiplier Tests for Panel Models. 

# Pooling Model
RoaPooling <- plm(ROA ~ GS + FirmSize + Leverage + Growth + Industry, data = RoaNoOut, model="pooling")
TobinPooling <- plm(TobinsQ ~ GS + FirmSize + Leverage + Growth + Industry, data = TobinNoOut, model="pooling")


# Plmtest
PlmtestRoa <- as.numeric(round(plmtest(RoaPooling, effect = "time", type = "bp")$p.value, digits = 3))
PlmtestTobin <- as.numeric(round(plmtest(TobinPooling, effect = "time", type = "bp")$p.value, digits = 3))

# Improve p-value understanding
PlmtestRoa<-ifelse(PlmtestRoa<0.01, paste(PlmtestRoa,"***",sep = ""),
	ifelse(PlmtestRoa<0.05,paste(PlmtestRoa,"**",sep = ""),
	ifelse(PlmtestRoa<0.1,paste(PlmtestRoa,"*",sep = ""), PlmtestRoa)))
PlmtestTobin<-ifelse(PlmtestTobin<0.01, paste(PlmtestTobin,"***",sep = ""),
	ifelse(PlmtestTobin<0.05,paste(PlmtestTobin,"**",sep = ""),
	ifelse(PlmtestTobin<0.1,paste(PlmtestTobin,"*",sep = ""),PlmtestTobin)))

# I test for Fixed Effect Model using pFtest which is a test of individual and/or time effects based on the comparison of the within and the pooling model.

# Within Model with time effect

RoaWithin <- plm(ROA ~ GS + FirmSize + Leverage + Growth + Industry, data = RoaNoOut, model = "within", effect = "time")
TobinWithin <- plm(TobinsQ ~ GS + FirmSize + Leverage + Growth + Industry, data = TobinNoOut, model = "within", effect = "time")

# pFtest

pFtestRoa <- round(pFtest(RoaWithin, RoaPooling)$p.value, digits = 3)

pFtestTobin <- round(pFtest(TobinWithin, TobinPooling)$p.value, digits = 3)

# Improve p-value understanding
pFtestRoa<-ifelse(pFtestRoa<0.01, paste(pFtestRoa,"***",sep = ""),
	ifelse(pFtestRoa<0.05,paste(pFtestRoa,"**",sep = ""),
	ifelse(pFtestRoa<0.1,paste(pFtestRoa,"*",sep = ""),pFtestRoa)))
pFtestTobin<-ifelse(pFtestTobin<0.01, paste(pFtestTobin,"***",sep = ""),
	ifelse(pFtestTobin<0.05,paste(pFtestTobin,"**",sep = ""),
	ifelse(pFtestTobin<0.1,paste(pFtestTobin,"*",sep = ""),pFtestTobin)))

# Let's consolidate into a stargazer table
titre <- "Green Score - an alternative variable for CEP"
stargazer(TobinPooling, 
        RoaWithin, 
        title = titre, 
        label = "GreenScoreResults", 
        single.row = TRUE,
        header = FALSE, 
        type = "latex", 
        align = FALSE, 
        model.numbers = FALSE, 
        table.placement = "!", 
        add.lines = list(c("BPLM test (pvalue)", PlmtestTobin, PlmtestRoa),
                         c("F test (pvalue)", pFtestTobin ,pFtestRoa)))
```

