---
title: "Lag2"
author: "Kinif Pierrick"
date: "5 avril 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, results = 'asis')
```

```{r}
#Download package and database


if (!require("plm")) install.packages("plm")
library(plm)
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
if (!require("utils")) install.packages("utils")
library(utils)

# I dowload my database befor knitting
# The excel file contains several sheets with all my data
# The csv file contains only variables of my model. Hence I dowload my DB with read.csv2

DB_Roa_Lagged<-data.frame(read.csv2("DataBase/Lagged2.csv", sep = ";",stringsAsFactors=FALSE, header = TRUE ))
DB_Tobin_Lagged <- filter(DB_Roa_Lagged, !is.na(TobinsQ))



## This DB will be used for analysis with my dependent variable = ROA

# From DB I select only row where TobinsQ <> zero . This database will be used when my dependent variable = TobinsQ

pdata.frame(DB_Roa_Lagged, index = c("Companies", "YearFinancialIndicator"))
pdata.frame(DB_Tobin_Lagged, index = c("Companies", "YearFinancialIndicator"))
```


# Lag vs not Lag With outliers

```{r}
#Test Lag vs not lag

if (!require("stargazer")) install.packages("stargazer")
library(stargazer)

M5_Lagged <- plm(ROA ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Roa_Lagged, index = c("Companies", "YearFinancialIndicator"))

M6_Lagged <- plm(TobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity  + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator) , model = "within", data = DB_Tobin_Lagged, index = c("Companies", "YearFinancialIndicator"))

Roe <- plm(ROE ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity  + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Roa_Lagged, index = c("Companies", "YearFinancialIndicator"))



stargazer(M5_Lagged, M6_Lagged, Roe,  table.placement = "h", type="latex", label = "Plm", title = "within Model M5, M6 et ROE with 2 lag", header = FALSE)




```

