---
title: "Attempt with others proxies"
author: "Kinif Pierrick"
date: "3 mai 2018"
output: html_document
---

```{r include = FALSE}
knitr :: opts_chunk$set(echo = TRUE, error = FALSE, message = FALSE, warning = FALSE, results = 'asis', tidy = TRUE)
```


```{r}
#############################################################
#############################################################
############## Package and DataBase loading #################
#############################################################
#############################################################

rm(list=ls()) #Removes all items in the environment!

#Packages
if (!require("utils")) install.packages("utils")
if (!require("dplyr")) install.packages("dplyr")
if (!require("plm")) install.packages("plm")
if (!require("stargazer")) install.packages("stargazer")
if (!require("xtable")) install.packages("xtable")
if (!require("data.table")) install.packages("data.table")

library(stargazer) # to create wonderful tables
library(plm) #to carry out regression
library(utils) #to write database in my folders
library(dplyr) #to play with data
library(data.table)
library(xtable)
#Database
DbLag1 <-as.data.frame(read.csv("DataBase/DataSynchronization/Lag1.csv", stringsAsFactors=FALSE, header = TRUE))

Model <- DbLag1 %>% select(c("CompaniesIndex",
                 "YearIndex",
                 "AlphaJensen",
                 "Roe",
                 "AlphaJensen",
                 "Roic",
                 "Ra",
                 "GreenScore",
                 "CarbonProductivity",
                 "WaterProductivity",
                 "WasteProductivity",
                 "EnergyProductivity",
                 "SustainabilityPayLink",
                 "SustainableThemedCommitment",
                 "AuditScore",
                 "TotalAssets",
                 "DebtToEquityRatio",
                 "NetMargin",
                 "GicsClassification",
                 "Beta",
                 "CostEquity",
                 "Eps"
                 )) 

# I make some little changes
Model$FirmSize <- log(Model$TotalAssets)
Model$LogEps <- log(Model$Eps)
setnames(Model, old = c("DebtToEquityRatio", "GicsClassification"), new = c("Leverage","Industry"))

```




```{r}

#####################################
####### 1// Remove Outliers #########
#####################################

# I define my models in lm as cooks.distance do not support plm object


Roe <- lm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

Roic <- lm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

Ra <- lm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

AlphaJensen <- lm(AlphaJensen ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)


## I calculate my cooks distance (i.e. D)
cooksdRoe <- cooks.distance(Roe)
cooksdRoic <- cooks.distance(Roic)
cooksdRa <- cooks.distance(Ra)
cooksdAlphaJensen <- cooks.distance(AlphaJensen)


## I extract rows considered as influential (observations whose D > 4 * means)

influentialRoe <- as.numeric(names(cooksdRoe)[(cooksdRoe > 4*mean(cooksdRoe, na.rm=T))])  
influentialRoic <- as.numeric(names(cooksdRoic)[(cooksdRoic > 4*mean(cooksdRoic, na.rm=T))])  
influentialRa <- as.numeric(names(cooksdRa)[(cooksdRa > 4*mean(cooksdRa, na.rm=T))])  
influentialAlphaJensen <- as.numeric(names(cooksdAlphaJensen)[(cooksdAlphaJensen > 4*mean(cooksdAlphaJensen, na.rm=T))])


#I remove outliers and create four new data frames that I write in my folders

Roe_Db <- Model[-c(influentialRoe),]

Roic_Db <- Model[-c(influentialRoic),]

Ra_Db <- Model[-c(influentialRa),]

AlphaJensen_Db <- Model[-c(influentialAlphaJensen),]
```






```{r}

#########################################################
##################### Plm Test ##########################
#########################################################

# See [@Park2011] , [@Torres-Reyna2010], [@Croissant2008], [@Bell2016b], [@Baltagi2008] for interprations

# I make my database pdataframe

Roe_Db <- pdata.frame(Roe_Db, index = c("CompaniesIndex","YearIndex"))
Roic_Db <- pdata.frame(Roic_Db, index = c("CompaniesIndex","YearIndex"))
Ra_Db <- pdata.frame(Ra_Db, index = c("CompaniesIndex","YearIndex"))
AlphaJensen_Db <- pdata.frame(AlphaJensen_Db, index = c("CompaniesIndex","YearIndex"))


#############
# A) LM test 
#############

#Roe
  PoolRoe<- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
    PlmtestRoe <- cbind("Roe", round(plmtest(PoolRoe, effect = "time", type = "bp")$p.value, digits = 4))

#Roic
  PoolRoic <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roic_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestRoic <- cbind("Roic", round(plmtest(PoolRoic, effect = "time", type = "bp")$p.value, digits = 4 ))

#Ra
  PoolRa <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestRa <- cbind("Ra", round(plmtest(PoolRa, effect = "time", type = "bp")$p.value, digits = 4 ))

#AlphaJensen
  PoolAlphaJensen <- plm(AlphaJensen ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = AlphaJensen_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestAlphaJensen <- cbind("AlphaJensen", round(plmtest(PoolAlphaJensen, effect = "time", type = "bp")$p.value, digits = 4 ))
  
#Summary in a table    
      
  PlmTable <- as.data.frame(rbind(PlmtestRoe, PlmtestRoic, PlmtestRa, PlmtestAlphaJensen))
  colnames(PlmTable) <- c("DependentVariables", "TimeEffect")
  rownames(PlmTable) <- c()
  PlmTable[,2] <- as.numeric(as.character(PlmTable[,2]))  

  # Improve p-value understanding
  PlmTable$TimeEffect<-ifelse(PlmTable$TimeEffect<0.01,"< .01 ***",
		ifelse(PlmTable$TimeEffect<0.05,"< .05 **",
		ifelse(PlmTable$TimeEffect<0.1,"< .1 *",PlmTable$TimeEffect)))
  
  #Xtable
  PlmTable1 <- xtable(PlmTable, caption = "Lagrange Multipliers test", label = "Breusch", align = "lll")
  
  print.xtable(PlmTable1, type = "html", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


  
  
#######################################################
# B) F test

#The argument of this function is whether a plms object or two plm objects, the first being a within model, the second a pooling model. The effects tested are whether individual, time or twoways effects depending on the effects introduced in the model.
#######################################################
  
  # Time Effect
  ###################
  

  FixedRoe<- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedRoic <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roic_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  FixedRa <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedAlphaJensen <- plm(AlphaJensen ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = AlphaJensen_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  #PfTest

  pFtestRoe <- cbind("Roe", round(pFtest(FixedRoe, PoolRoe, effect = "time")$p.value, digits = 4 ))
  
  pFtestRoic <- cbind("Roic", round(pFtest(FixedRoic, PoolRoic, effect = "time")$p.value, digits = 4 ))
  
  pFtestRa <- cbind("Ra", round(pFtest(FixedRa, PoolRa, effect = "time")$p.value, digits = 4 ))
  
  pFtestAlphaJensen <- cbind("AlphaJensen", round(pFtest(FixedAlphaJensen, PoolAlphaJensen, effect = "time")$p.value, digits = 4 ))

#Summary in a table    
      
  pFtestTable <- as.data.frame(rbind(pFtestRoe, pFtestRoic, pFtestRa, pFtestAlphaJensen))
  colnames(pFtestTable) <- c("DependentVariables", "TimeEffect")
  rownames(pFtestTable) <- c()
  pFtestTable[,2] <- as.numeric(as.character(pFtestTable[,2]))  

  # Improve p-value understanding
  pFtestTable$TimeEffect<-ifelse(pFtestTable$TimeEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$TimeEffect<0.05,"< .05 **",
		ifelse(pFtestTable$TimeEffect<0.1,"< .1 *",pFtestTable$TimeEffect)))
  
  #Xtable
  pFtestTable1 <- xtable(pFtestTable, caption = "F test ", label = "pFtest", align = "lll")
  
  print.xtable(pFtestTable1, type = "html", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))

  
  
```
  

  
```{r}

####################################################################################
####################################################################################
########################## Regression Analysis Reporting ###########################
####################################################################################
####################################################################################

stargazer(PoolRoe, summary = FALSE, title = "Regression results - Pooled Ols estimation", label = "Roe", header = FALSE, type = "html")

stargazer(FixedRoic, FixedRa, FixedAlphaJensen, summary = FALSE, title = "Regression results - FE estimation", label = "FE", header = FALSE, type = "html")

```
  
  
  

  
  
  







