---
output : pdf_document
---

```{r include = FALSE}
knitr :: opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE, results = 'asis', tidy = TRUE)
```


```{r}
#############################################################
#############################################################
############## Package and DataBase loading #################
#############################################################
#############################################################

rm(list=ls()) #Removes all items in the environment!

#Packages
if (!require("utils")) install.packages("utils")
if (!require("dplyr")) install.packages("dplyr")
if (!require("plm")) install.packages("plm")
if (!require("stargazer")) install.packages("stargazer")
if (!require("xtable")) install.packages("xtable")
if (!require("data.table")) install.packages("data.table")

library(stargazer) # to create wonderful tables
library(plm) #to carry out regression
library(utils) #to write database in my folders
library(dplyr) #to play with data
library(data.table)
library(xtable)

#Database
DbLag1 <-as.data.frame(read.csv("DataBase/DataSynchronization/Lag2.csv", stringsAsFactors=FALSE, header = TRUE))

Model <- DbLag1 %>% select(c("CompaniesIndex",
                 "YearIndex",
                 "Ra",
                 "Roa",
                 "StockPriceClose",
                 "TobinsQ",
                 "PriceToEarningRatio",
                 "PriceToEpsRatio",
                 "GreenScore",
                 "CarbonProductivity",
                 "WaterProductivity",
                 "WasteProductivity",
                 "EnergyProductivity",
                 "SustainabilityPayLink",
                 "SustainableThemedCommitment",
                 "AuditScore",
                 "TotalAssets",
                 "DebtToEquityRatio",
                 "NetMargin",
                 "GicsClassification",
                 "Beta",
                 "CostEquity",
                 "Eps"
                 )) 

# I make some little changes
Model$FirmSize <- log(Model$TotalAssets)
Model$LogTobinsQ <- log(Model$TobinsQ)
Model$LogPriceToEarningRatio <- log(Model$PriceToEarningRatio)
Model$LogEps <- log(Model$Eps)
Model$LogStockPrice <- log(Model$StockPriceClose)
Model$LogPriceToEpsRatio <- log(Model$PriceToEpsRatio)

setnames(Model, old = c("DebtToEquityRatio", "GicsClassification"), new = c("Leverage","Industry"))

```




```{r}

#####################################
####### 1// Remove Outliers #########
#####################################

# I define my models in lm as cooks.distance do not support plm object
LogEps <-lm(LogEps ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  + YearIndex , data = Model)

TobinsQ<-lm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

LogStockPrice <- lm(LogStockPrice ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

LogPriceToEpsRatio <- lm(LogPriceToEpsRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

Ra <- lm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

PriceToEarningRatio <- lm(LogPriceToEarningRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)


## I calculate my cooks distance (i.e. D)
cooksdLogEps <- cooks.distance(LogEps)
cooksdTobinsQ <- cooks.distance(TobinsQ)
cooksdLogStockPrice <- cooks.distance(LogStockPrice)
cooksdLogPriceToEpsRatio <- cooks.distance(LogPriceToEpsRatio)
cooksdRa <- cooks.distance(Ra)
cooksdPriceToEarningRatio <- cooks.distance(PriceToEarningRatio)


## I extract rows considered as influential (observations whose D > 4 * means)

influentialLogEps <- as.numeric(names(cooksdLogEps)[(cooksdLogEps > 4*mean(cooksdLogEps, na.rm=T))])  
influentialTobin <- as.numeric(names(cooksdTobinsQ)[(cooksdTobinsQ > 4*mean(cooksdTobinsQ, na.rm=T))])  
influentialLogStockPrice <- as.numeric(names(cooksdLogStockPrice)[(cooksdLogStockPrice > 4*mean(cooksdLogStockPrice, na.rm=T))])  
influentialLogPriceToEpsRatio <- as.numeric(names(cooksdLogPriceToEpsRatio)[(cooksdLogPriceToEpsRatio > 4*mean(cooksdLogPriceToEpsRatio, na.rm=T))])  
influentialRa <- as.numeric(names(cooksdRa)[(cooksdRa > 4*mean(cooksdRa, na.rm=T))])  
influentialPriceToEarningRatio <- as.numeric(names(cooksdPriceToEarningRatio)[(cooksdPriceToEarningRatio > 4*mean(cooksdPriceToEarningRatio, na.rm=T))])


head(Model[influentialLogEps, ])  # influential observations 
head(Model[influentialTobin, ])  # influential observations 
head(Model[influentialLogStockPrice, ])  # influential observations 
head(Model[influentialLogPriceToEpsRatio, ])  # influential observations 
head(Model[influentialRa, ])  # influential observations 
head(Model[influentialPriceToEarningRatio, ])  # influential observations 

#I remove outliers and create four new data frames that I write in my folders

TobinsQ_Db <- Model[-c(influentialTobin),]

LogEps_Db <- Model[-c(influentialLogEps),]

LogStockPrice_Db <- Model[-c(influentialLogStockPrice),]

LogPriceToEpsRatio_Db <- Model[-c(influentialLogPriceToEpsRatio),]

Ra_Db <- Model[-c(influentialRa),]

PriceToEarningRatio_Db <- Model[-c(influentialPriceToEarningRatio),]
```






```{r}

#########################################################
##################### Plm Test ##########################
#########################################################

# See [@Park2011] , [@Torres-Reyna2010], [@Croissant2008], [@Bell2016b], [@Baltagi2008] for interprations

# I make my database pdataframe

TobinsQ_Db <- pdata.frame(TobinsQ_Db, index = c("CompaniesIndex","YearIndex"))
LogEps_Db <- pdata.frame(LogEps_Db, index = c("CompaniesIndex","YearIndex"))
LogStockPrice_Db <- pdata.frame(LogStockPrice_Db, index = c("CompaniesIndex","YearIndex"))
LogPriceToEpsRatio_Db <- pdata.frame(LogPriceToEpsRatio_Db, index = c("CompaniesIndex","YearIndex"))
Ra_Db <- pdata.frame(Ra_Db, index = c("CompaniesIndex","YearIndex"))
PriceToEarningRatio_Db <- pdata.frame(PriceToEarningRatio_Db, index = c("CompaniesIndex","YearIndex"))


#######################################################
# A) LM test for random effects versus OLS
#######################################################

#TobinsQ
  PoolTobinsQ<- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))

  PlmtestTobinsQ <- cbind("TobinsQ", round(plmtest(PoolTobinsQ, effect = "time", type = "bp")$p.value, digits = 4), round(plmtest(PoolTobinsQ, effect = "individual", type = "bp")$p.value, digits = 4), round(plmtest(PoolTobinsQ, effect = "twoways", type = "bp")$p.value, digits = 4)) 
  
#LogEps
  PoolLogEps <- plm(LogEps ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogEps_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestLogEps <- cbind("LogEps", round(plmtest(PoolLogEps, effect = "time", type = "bp")$p.value, digits = 4), round(plmtest(PoolLogEps, effect = "individual", type = "bp")$p.value, digits = 4), round(plmtest(PoolLogEps, effect = "twoways", type = "bp")$p.value, digits = 4))

#LogStockPrice
  PoolLogStockPrice<- plm(LogStockPrice ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogStockPrice_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
    PlmtestLogStockPrice <- cbind("LogStockPrice", round(plmtest(PoolLogStockPrice, effect = "time", type = "bp")$p.value, digits = 4), round(plmtest(PoolLogStockPrice, effect = "individual", type = "bp")$p.value, digits = 4), round(plmtest(PoolLogStockPrice, effect = "twoways", type = "bp")$p.value, digits = 4))

#LogPriceToEpsRatio
  PoolLogPriceToEpsRatio <- plm(LogPriceToEpsRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEpsRatio_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestLogPriceToEpsRatio <- cbind("LogPriceToEpsRatio", round(plmtest(PoolLogPriceToEpsRatio, effect = "time", type = "bp")$p.value, digits = 4 ),  round(plmtest(PoolLogPriceToEpsRatio, effect = "individual", type = "bp")$p.value, digits = 4 ), round(plmtest(PoolLogPriceToEpsRatio, effect = "twoways", type = "bp")$p.value, digits = 4))

#Ra
  PoolRa <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestRa <- cbind("Ra", round(plmtest(PoolRa, effect = "time", type = "bp")$p.value, digits = 4 ),  round(plmtest(PoolRa, effect = "individual", type = "bp")$p.value, digits = 4 ), round(plmtest(PoolRa, effect = "twoways", type = "bp")$p.value, digits = 4))

#PriceToEarningRatio
  PoolPriceToEarningRatio <- plm(LogPriceToEarningRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = PriceToEarningRatio_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestPriceToEarningRatio <- cbind("PriceToEarningRatio", round(plmtest(PoolPriceToEarningRatio, effect = "time", type = "bp")$p.value, digits = 4 ),  round(plmtest(PoolPriceToEarningRatio, effect = "individual", type = "bp")$p.value, digits = 4 ), round(plmtest(PoolPriceToEarningRatio, effect = "twoways", type = "bp")$p.value, digits = 4))
  
  
  
#Summary in a table    
      
  PlmTable <- as.data.frame(rbind(PlmtestTobinsQ, PlmtestLogEps, PlmtestLogStockPrice, PlmtestLogPriceToEpsRatio, PlmtestRa, PlmtestPriceToEarningRatio))
  colnames(PlmTable) <- c("DependentVariables", "TimeEffect", "IndividualEffect", "TwowaysEffect")
  rownames(PlmTable) <- c()
  PlmTable[,2] <- as.numeric(as.character(PlmTable[,2]))  
  PlmTable[,3] <- as.numeric(as.character(PlmTable[,3]))  
  PlmTable[,4] <- as.numeric(as.character(PlmTable[,4]))  
  
  # Improve p-value understanding
  PlmTable$TimeEffect<-ifelse(PlmTable$TimeEffect<0.01,"< .01 ***",
		ifelse(PlmTable$TimeEffect<0.05,"< .05 **",
		ifelse(PlmTable$TimeEffect<0.1,"< .1 *",PlmTable$TimeEffect)))
  
  PlmTable$IndividualEffect<-ifelse(PlmTable$IndividualEffect<0.01,"< .01 ***",
		ifelse(PlmTable$IndividualEffect<0.05,"< .05 **",
		ifelse(PlmTable$IndividualEffect<0.1,"< .1 *",PlmTable$IndividualEffect)))     

  PlmTable$TwowaysEffect<-ifelse(PlmTable$TwowaysEffect<0.01,"< .01 ***",
		ifelse(PlmTable$TwowaysEffect<0.05,"< .05 **",
		ifelse(PlmTable$TwowaysEffect<0.1,"< .1 *",PlmTable$TwowaysEffect))) 
  
  #Xtable
  PlmTable1 <- xtable(PlmTable, caption = "Lagrange Multipliers test for random effects versus OLS", label = "Breusch", align = "lllll")
  
  print.xtable(PlmTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))


  
  
#######################################################
# B) F test for Random effects versus OLS

#The argument of this function is whether a plms object or two plm objects, the first being a within model, the second a pooling model. The effects tested are whether individual, time or twoways effects depending on the effects introduced in the model.
#######################################################
  
  # Time Effect
  ###################
  
  FixedTobinsQ<- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  FixedLogEps<- plm(LogEps ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogEps_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedLogStockPrice<- plm(LogStockPrice ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogStockPrice_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedLogPriceToEpsRatio <- plm(LogPriceToEpsRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEpsRatio_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  FixedRa <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")


  FixedPriceToEarningRatio <- plm(LogPriceToEarningRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = PriceToEarningRatio_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  # Individual Effect
  ###################
  
  FixedTobinsQ1 <- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")
  
  FixedLogEps1 <- plm(LogEps ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogEps_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")

  FixedLogStockPrice1 <- plm(LogStockPrice ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogStockPrice_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")

  FixedLogPriceToEpsRatio1 <- plm(LogPriceToEpsRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEpsRatio_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")
  
  FixedRa1 <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")

  FixedPriceToEarningRatio1 <- plm(LogPriceToEarningRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = PriceToEarningRatio_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")
  
  # TwoWays Effect
  ###################
  
  FixedTobinsQ2 <- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")
  
  FixedLogEps2 <- plm(LogEps ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogEps_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")

  FixedLogStockPrice2 <- plm(LogStockPrice ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogStockPrice_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")

  FixedLogPriceToEpsRatio2 <- plm(LogPriceToEpsRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEpsRatio_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")
  
  FixedRa2 <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")

  FixedPriceToEarningRatio2 <- plm(LogPriceToEarningRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = PriceToEarningRatio_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")
  
  #PfTest
  pFtestTobinsQ <- cbind("TobinsQ", round(pFtest(FixedTobinsQ, PoolTobinsQ, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedTobinsQ1, PoolTobinsQ, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedTobinsQ2, PoolTobinsQ, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestLogEps <- cbind("LogEps", round(pFtest(FixedLogEps, PoolLogEps, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedLogEps1, PoolLogEps, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedLogEps2, PoolLogEps, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestLogStockPrice <- cbind("LogStockPrice", round(pFtest(FixedLogStockPrice, PoolLogStockPrice, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedLogStockPrice1, PoolLogStockPrice, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedLogStockPrice2, PoolLogStockPrice, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestLogPriceToEpsRatio <- cbind("LogPriceToEpsRatio", round(pFtest(FixedLogPriceToEpsRatio, PoolLogPriceToEpsRatio, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedLogPriceToEpsRatio1, PoolLogPriceToEpsRatio, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedLogPriceToEpsRatio2, PoolLogPriceToEpsRatio, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestRa <- cbind("Ra", round(pFtest(FixedRa, PoolRa, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedRa1, PoolRa, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedRa2, PoolRa, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestPriceToEarningRatio <- cbind("PriceToEarningRatio", round(pFtest(FixedPriceToEarningRatio, PoolPriceToEarningRatio, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedPriceToEarningRatio1, PoolPriceToEarningRatio, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedPriceToEarningRatio2, PoolPriceToEarningRatio, effect = "twoways")$p.value, digits = 4 ))

#Summary in a table    
      
  pFtestTable <- as.data.frame(rbind(pFtestTobinsQ, pFtestLogEps, pFtestLogStockPrice, pFtestLogPriceToEpsRatio, pFtestRa, pFtestPriceToEarningRatio))
  colnames(pFtestTable) <- c("DependentVariables", "TimeEffect", "IndividualEffect", "TwowaysEffect")
  rownames(pFtestTable) <- c()
  pFtestTable[,2] <- as.numeric(as.character(pFtestTable[,2]))  
  pFtestTable[,3] <- as.numeric(as.character(pFtestTable[,3]))  
  pFtestTable[,4] <- as.numeric(as.character(pFtestTable[,4]))  
  
  # Improve p-value understanding
  pFtestTable$TimeEffect<-ifelse(pFtestTable$TimeEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$TimeEffect<0.05,"< .05 **",
		ifelse(pFtestTable$TimeEffect<0.1,"< .1 *",pFtestTable$TimeEffect)))
  
  pFtestTable$IndividualEffect<-ifelse(pFtestTable$IndividualEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$IndividualEffect<0.05,"< .05 **",
		ifelse(pFtestTable$IndividualEffect<0.1,"< .1 *",pFtestTable$IndividualEffect)))     

  pFtestTable$TwowaysEffect<-ifelse(pFtestTable$TwowaysEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$TwowaysEffect<0.05,"< .05 **",
		ifelse(pFtestTable$TwowaysEffect<0.1,"< .1 *",pFtestTable$TwowaysEffect))) 
  
  #Xtable
  pFtestTable1 <- xtable(pFtestTable, caption = "F test for fixed effects versus OLS", label = "pFtest", align = "lllll")
  
  print.xtable(pFtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))


  
  
#######################################################
# C) Hausman Test
# phtest computes the Hausman test which is based on the comparison of two sets of estimates (see Hausman 1978). Its main arguments are two panelmodel objects or a formula. A classical application of the Hausman test for panel data is to compare the Random and the random effects models. 
#######################################################

  RandomTobinsQ<- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="random", index = c("CompaniesIndex","YearIndex"))
  
  RandomLogEps<- plm(LogEps ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogEps_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomLogStockPrice<- plm(LogStockPrice ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogStockPrice_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomLogPriceToEpsRatio <- plm(LogPriceToEpsRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEpsRatio_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomRa <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="random", index = c("CompaniesIndex","YearIndex"))
  
  RandomPriceToEarningRatio <- plm(LogPriceToEarningRatio ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = PriceToEarningRatio_Db, model="random", index = c("CompaniesIndex","YearIndex"))

### Hausman test with time fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ, RandomTobinsQ)$p.value, digits = 4 ))
  phtestLogEps <- cbind("LogEps", round(phtest(FixedLogEps, RandomLogEps)$p.value, digits = 4 ))
  phtestLogStockPrice <- cbind("LogStockPrice", round(phtest(FixedLogStockPrice, RandomLogStockPrice)$p.value, digits = 4 ))
  phtestLogPriceToEpsRatio <- cbind("LogPriceToEpsRatio", round(phtest(FixedLogPriceToEpsRatio, RandomLogPriceToEpsRatio)$p.value, digits = 4 ))
  phtestRa <- cbind("Ra", round(phtest(FixedRa, RandomRa)$p.value, digits = 4 ))
  phtestPriceToEarningRatio <- cbind("PriceToEarningRatio", round(phtest(FixedPriceToEarningRatio, RandomPriceToEarningRatio)$p.value, digits = 4 ))
  


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestLogEps, phtestLogStockPrice, phtestLogPriceToEpsRatio, phtestRa, phtestPriceToEarningRatio))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with time effect in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))


### Hausman test with indivudals fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ1, RandomTobinsQ)$p.value, digits = 4 ))
  phtestLogEps <- cbind("LogEps", round(phtest(FixedLogEps1, RandomLogEps)$p.value, digits = 4 ))
  phtestLogStockPrice <- cbind("LogStockPrice", round(phtest(FixedLogStockPrice1, RandomLogStockPrice)$p.value, digits = 4 ))
  phtestLogPriceToEpsRatio <- cbind("LogPriceToEpsRatio", round(phtest(FixedLogPriceToEpsRatio1, RandomLogPriceToEpsRatio)$p.value, digits = 4 ))
  phtestRa <- cbind("Ra", round(phtest(FixedRa1, RandomRa)$p.value, digits = 4 ))
  phtestPriceToEarningRatio <- cbind("PriceToEarningRatio", round(phtest(FixedPriceToEarningRatio1, RandomPriceToEarningRatio)$p.value, digits = 4 ))


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestLogEps, phtestLogStockPrice, phtestLogPriceToEpsRatio, phtestRa, phtestPriceToEarningRatio))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with individual effect in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))
  
### Hausman test with twoways fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ2, RandomTobinsQ)$p.value, digits = 4 ))
  phtestLogEps <- cbind("LogEps", round(phtest(FixedLogEps2, RandomLogEps)$p.value, digits = 4 ))
  phtestLogStockPrice <- cbind("LogStockPrice", round(phtest(FixedLogStockPrice2, RandomLogStockPrice)$p.value, digits = 4 ))
  phtestLogPriceToEpsRatio <- cbind("LogPriceToEpsRatio", round(phtest(FixedLogPriceToEpsRatio2, RandomLogPriceToEpsRatio)$p.value, digits = 4 ))
  phtestRa <- cbind("Ra", round(phtest(FixedRa2, RandomRa)$p.value, digits = 4 ))
  phtestPriceToEarningRatio <- cbind("PriceToEarningRatio", round(phtest(FixedPriceToEarningRatio2, RandomPriceToEarningRatio)$p.value, digits = 4 ))


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestLogEps, phtestLogStockPrice, phtestLogPriceToEpsRatio, phtestRa, phtestPriceToEarningRatio))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with twoways effects in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))
  
  
  
  
  
  
```
  

  
```{r}

####################################################################################
####################################################################################
########################## Regression Analysis Reporting ###########################
####################################################################################
####################################################################################

# TobinsQ
stargazer(PoolTobinsQ, RandomTobinsQ, summary = FALSE, title = "Model comparison TobinsQ - Pool (1), Random (2)", label = "TobinsQ", header = FALSE)

stargazer(FixedTobinsQ, FixedTobinsQ1, FixedTobinsQ2, summary = FALSE, title = "Model comparison TobinsQ - Fixed with time (1), individual (2) and twoways effects (3)", label = "TobinsQ1", header = FALSE)

# LogEps
stargazer(PoolLogEps, RandomLogEps, summary = FALSE, title = "Model comparison LogEps - Pool (1), Random (2)", label = "LogEps", header = FALSE)

stargazer(FixedLogEps, FixedLogEps1, FixedLogEps2, summary = FALSE, title = "Model comparison LogEps - Fixed with time (1), individual (2) and twoways effects (3)", label = "LogEps1", header = FALSE)

#LogStockPrice
stargazer(PoolLogStockPrice, RandomLogStockPrice, summary = FALSE, title = "Model comparison LogStockPrice - Pool (1), Random (2)", label = "LogStockPrice", header = FALSE)

stargazer(FixedLogStockPrice, FixedLogStockPrice1, FixedLogStockPrice2, summary = FALSE, title = "Model comparison LogStockPrice - Fixed with time (1), individual (2) and twoways effects (3)", label = "LogStockPrice1", header = FALSE)

#LogPriceToEpsRatio
stargazer(PoolLogPriceToEpsRatio, RandomLogPriceToEpsRatio, summary = FALSE, title = "Model comparison LogPriceToEpsRatio - Pool (1), Random (2)", label = "LogPriceToEpsRatio", header = FALSE)

stargazer(FixedLogPriceToEpsRatio, FixedLogPriceToEpsRatio1, FixedLogPriceToEpsRatio2, summary = FALSE, title = "Model comparison LogPriceToEpsRatio - Fixed with time (1), individual (2) and twoways effects (3)", label = "LogPriceToEpsRatio1", header = FALSE)

#Ra
stargazer(PoolRa, RandomRa, summary = FALSE, title = "Model comparison Ra - Pool (1), Random (2)", label = "Ra", header = FALSE)

stargazer(FixedRa, FixedRa1, FixedRa2, summary = FALSE, title = "Model comparison Ra - Fixed with time (1), individual (2) and twoways effects (3)", label = "Ra1", header = FALSE)

#PriceToEarningRatio
stargazer(PoolPriceToEarningRatio, RandomPriceToEarningRatio, summary = FALSE, title = "Model comparison PriceToEarningRatio - Pool (1), Random (2)", label = "PriceToEarningRatio", header = FALSE)

stargazer(FixedPriceToEarningRatio, FixedPriceToEarningRatio1, FixedPriceToEarningRatio2, summary = FALSE, title = "Model comparison PriceToEarningRatio - Fixed with time (1), individual (2) and twoways effects (3)", label = "PriceToEarningRatio1", header = FALSE)



# Based on test, I have to use pooling for both Tobin and LogStockPrice and fixed effect for both LogEps and LogPriceToEpsRatio. 

stargazer(FixedLogEps, PoolLogStockPrice, summary = FALSE, header= FALSE, label = "summary", title = "Model based on LM, wild and hausmand test")

stargazer(PoolTobinsQ, FixedLogPriceToEpsRatio, summary = FALSE, header= FALSE, label = "summary", title = "Model based on LM, wild and hausmand test")

```
  
  
  
  
  
```{r}


################################################################################
################################################################################
##################### Green Score :))))))       ################################
################################################################################
################################################################################



###################################
# Remove Outliers
###################################

TobinsQ <- lm(LogTobinsQ ~ GreenScore + FirmSize + Leverage + Industry + NetMargin, data = Model)
LogPriceToEarningRatio <- lm(LogPriceToEarningRatio ~ GreenScore + FirmSize + Leverage + Industry + NetMargin, data = Model)
LogStockPrice <- lm(LogStockPrice ~ GreenScore + FirmSize + Leverage + Industry + NetMargin, data = Model)
LogPriceToEpsRatio <- lm(LogTobinsQ ~ GreenScore + FirmSize + Leverage + Industry + NetMargin, data = Model)

cooksdLogPriceToEarningRatio <- cooks.distance(LogPriceToEarningRatio)
cooksdTobinsQ <- cooks.distance(TobinsQ)
cooksdLogStockPrice <- cooks.distance(LogStockPrice)
cooksdLogPriceToEpsRatio <- cooks.distance(LogPriceToEpsRatio)

## I extract rows considered as influential (observations whose D > 4 * means)

influentialLogPriceToEarningRatio <- as.numeric(names(cooksdLogPriceToEarningRatio)[(cooksdLogPriceToEarningRatio > 4*mean(cooksdLogPriceToEarningRatio, na.rm=T))])  
influentialTobin <- as.numeric(names(cooksdTobinsQ)[(cooksdTobinsQ > 4*mean(cooksdTobinsQ, na.rm=T))])  
influentialLogStockPrice <- as.numeric(names(cooksdLogStockPrice)[(cooksdLogStockPrice > 4*mean(cooksdLogStockPrice, na.rm=T))])  
influentialLogPriceToEpsRatio <- as.numeric(names(cooksdLogPriceToEpsRatio)[(cooksdLogPriceToEpsRatio > 4*mean(cooksdLogPriceToEpsRatio, na.rm=T))])  



head(Model[influentialLogPriceToEarningRatio, ])  # influential observations 
head(Model[influentialTobin, ])  # influential observations 
head(Model[influentialLogStockPrice, ])  # influential observations 
head(Model[influentialLogPriceToEpsRatio, ])  # influential observations 


#I remove outliers and create four new data frames that I write in my folders

TobinsQ_Db <- Model[-c(influentialTobin),]

LogPriceToEarningRatio_Db <- Model[-c(influentialLogPriceToEarningRatio),]

LogStockPrice_Db <- Model[-c(influentialLogStockPrice),]

LogPriceToEpsRatio_Db <- Model[-c(influentialLogPriceToEpsRatio),]



# I make my database pdataframe

TobinsQ_Db <- pdata.frame(TobinsQ_Db, index = c("CompaniesIndex","YearIndex"))
LogPriceToEarningRatio_Db <- pdata.frame(LogPriceToEarningRatio_Db, index = c("CompaniesIndex","YearIndex"))
LogStockPrice_Db <- pdata.frame(LogStockPrice_Db, index = c("CompaniesIndex","YearIndex"))
LogPriceToEpsRatio_Db <- pdata.frame(LogPriceToEpsRatio_Db, index = c("CompaniesIndex","YearIndex"))



#######################################################
# A) LM test for random effects versus OLS
#######################################################

#TobinsQ
  PoolTobinsQ<- plm(LogTobinsQ ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))

  PlmtestTobinsQ <- cbind("TobinsQ", round(plmtest(PoolTobinsQ, effect = "time", type = "bp")$p.value, digits = 4))
  
#LogPriceToEarningRatio
  PoolLogPriceToEarningRatio <- plm(LogPriceToEarningRatio ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEarningRatio_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestLogPriceToEarningRatio <- cbind("LogPriceToEarningRatio", round(plmtest(PoolLogPriceToEarningRatio, effect = "time", type = "bp")$p.value, digits = 4))
#LogStockPrice
  PoolLogStockPrice<- plm(LogStockPrice ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = LogStockPrice_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
    PlmtestLogStockPrice <- cbind("LogStockPrice", round(plmtest(PoolLogStockPrice, effect = "time", type = "bp")$p.value, digits = 4))

#LogPriceToEpsRatio
  PoolLogPriceToEpsRatio <- plm(LogPriceToEpsRatio ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEpsRatio_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestLogPriceToEpsRatio <- cbind("LogPriceToEpsRatio", round(plmtest(PoolLogPriceToEpsRatio, effect = "time", type = "bp")$p.value, digits = 4 ))


#Summary in a table    
      
  PlmTable <- as.data.frame(rbind(PlmtestTobinsQ, PlmtestLogPriceToEarningRatio, PlmtestLogStockPrice, PlmtestLogPriceToEpsRatio))
  colnames(PlmTable) <- c("DependentVariables", "TimeEffect")
  rownames(PlmTable) <- c()
  PlmTable[,2] <- as.numeric(as.character(PlmTable[,2]))  

  # Improve p-value understanding
  PlmTable$TimeEffect<-ifelse(PlmTable$TimeEffect<0.01,"< .01 ***",
		ifelse(PlmTable$TimeEffect<0.05,"< .05 **",
		ifelse(PlmTable$TimeEffect<0.1,"< .1 *",PlmTable$TimeEffect)))
 
 
  #Xtable
  PlmTable1 <- xtable(PlmTable, caption = "Lagrange Multipliers test for random effects versus OLS", label = "Breusch", align = "lll")
  
  print.xtable(PlmTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


#######################################################
# B) F / Wilrd test for Fixed effects versus OLS
#######################################################
  
  # Time Effect
  ###################
  
  FixedTobinsQ<- plm(LogTobinsQ ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  FixedLogPriceToEarningRatio<- plm(LogPriceToEarningRatio ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEarningRatio_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedLogStockPrice<- plm(LogStockPrice ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = LogStockPrice_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedLogPriceToEpsRatio <- plm(LogPriceToEpsRatio ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEpsRatio_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")



  #PfTest
  pFtestTobinsQ <- cbind("TobinsQ", round(pFtest(FixedTobinsQ, PoolTobinsQ, effect = "time")$p.value, digits = 4 ))
  
  pFtestLogPriceToEarningRatio <- cbind("LogPriceToEarningRatio", round(pFtest(FixedLogPriceToEarningRatio, PoolLogPriceToEarningRatio, effect = "time")$p.value, digits = 4 ))
  
  pFtestLogStockPrice <- cbind("LogStockPrice", round(pFtest(FixedLogStockPrice, PoolLogStockPrice, effect = "time")$p.value, digits = 4 ))
  
  pFtestLogPriceToEpsRatio <- cbind("LogPriceToEpsRatio", round(pFtest(FixedLogPriceToEpsRatio, PoolLogPriceToEpsRatio, effect = "time")$p.value, digits = 4 ))
  

#Summary in a table    
      
  pFtestTable <- as.data.frame(rbind(pFtestTobinsQ, pFtestLogPriceToEarningRatio, pFtestLogStockPrice, pFtestLogPriceToEpsRatio))
  colnames(pFtestTable) <- c("DependentVariables", "TimeEffect")
  rownames(pFtestTable) <- c()
  pFtestTable[,2] <- as.numeric(as.character(pFtestTable[,2]))  

  # Improve p-value understanding
  pFtestTable$TimeEffect<-ifelse(pFtestTable$TimeEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$TimeEffect<0.05,"< .05 **",
		ifelse(pFtestTable$TimeEffect<0.1,"< .1 *",pFtestTable$TimeEffect)))

  #Xtable
  pFtestTable1 <- xtable(pFtestTable, caption = "F test for fixed effects versus OLS", label = "pFtest", align = "lll")
  
  print.xtable(pFtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


#######################################################
# C) Hausman Test
#######################################################

  RandomTobinsQ<- plm(LogTobinsQ ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="random", index = c("CompaniesIndex","YearIndex"))
  
  RandomLogPriceToEarningRatio<- plm(LogPriceToEarningRatio ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEarningRatio_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomLogStockPrice<- plm(LogStockPrice ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = LogStockPrice_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomLogPriceToEpsRatio <- plm(LogPriceToEpsRatio ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = LogPriceToEpsRatio_Db, model="random", index = c("CompaniesIndex","YearIndex"))



### Hausman test with time fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ, RandomTobinsQ)$p.value, digits = 4 ))
  phtestLogPriceToEarningRatio <- cbind("LogPriceToEarningRatio", round(phtest(FixedLogPriceToEarningRatio, RandomLogPriceToEarningRatio)$p.value, digits = 4 ))
  phtestLogStockPrice <- cbind("LogStockPrice", round(phtest(FixedLogStockPrice, RandomLogStockPrice)$p.value, digits = 4 ))
  phtestLogPriceToEpsRatio <- cbind("LogPriceToEpsRatio", round(phtest(FixedLogPriceToEpsRatio, RandomLogPriceToEpsRatio)$p.value, digits = 4 ))

  


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestLogPriceToEarningRatio, phtestLogStockPrice, phtestLogPriceToEpsRatio))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with time effect in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


#######################################################
# D) Result Reporting
#######################################################
  
stargazer(FixedLogPriceToEarningRatio, FixedLogPriceToEpsRatio, summary = FALSE, title = " Fixed Model", label = "GreenScore", header = FALSE)
stargazer(PoolLogPriceToEarningRatio, PoolLogPriceToEpsRatio, summary = FALSE, title = "Pool  Model", label = "GreenScore", header = FALSE)

  
```
  
  
  







