---
title: "EndogeneityTest"
author: "Kinif Pierrick"
date: "5 avril 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, results = 'asis')
```

```{r}
if (!require("systemfit")) install.packages("systemfit")
library(systemfit)
if (!require("plm")) install.packages("plm")
library(plm)
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
if (!require("utils")) install.packages("utils")
library(utils)

# I dowload my database befor knitting
# The excel file contains several sheets with all my data
# The csv file contains only variables of my model. Hence I dowload my DB with read.csv2
DB_Roa<-data.frame(read.csv2("DataBase/DataBase_010418.csv", sep = ";",stringsAsFactors=FALSE, header = TRUE ))
write.csv2(DB_Roa, file = "DataBase/DB_Roa.csv")
## This DB will be used for analysis with my dependent variable = ROA

# From DB I select only row where TobinsQ <> zero . This database will be used when my dependent variable = TobinsQ

DB_Tobin <- filter(DB_Roa, !is.na(TobinsQ))
write.csv2(DB_Tobin, file = "DataBase/DB_Tobin.csv")
```


```{r}

PanelDataTobin  <- pdata.frame(DB_Tobin, index = c("Companies","YearFinancialIndicator"))
PanelDataRoa <- pdata.frame(DB_Roa, index = c("Companies","YearFinancialIndicator"))


TwoSLS5 <- systemfit(TobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry, method = "SUR", data = PanelDataTobin)

ThreeSLS5 <- systemfit(TobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry, method = "3SLS", data = PanelDataTobin)


TwoSLS6 <- systemfit(ROA ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry, method = "SUR", data = PanelDataRoa)

ThreeSLS6 <- systemfit(ROA ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry, method = "3SLS", data = PanelDataRoa)

hausman.systemfit(TwoSLS5,ThreeSLS5)
hausman.systemfit(TwoSLS6,ThreeSLS6)
```

