---
title: "Endogeneity"
author: "Kinif Pierrick"
date: "10 avril 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Literature Review Endogeneity

## What is endogeneity ?

Citation from [@Roberts2013]

> the most important and pervasive issue confronting studies in empirical corporate finance is endogeneity, which we can loosely define as a correlation between the explanatory variables and the error term in a regression. Endogeneity leads to biased and inconsistent parameter estimates that make reliable inference virtually impossible.

> researchers must make clear which variable(s) are endogenous and why they are endogenous

Having endogeneity in a economretric model implies that OLS is not applicable. Endogeneity reject assumption 4 of OLS model, namely an error term that is uncorrelated with each explanatory variable.

The following citation is **extremely important** : 

> Assumption 4 (or 4a) should be the focus of most research designs because violation of this assumption is the primary cause of inference problems. Yet, this condition is empirically untestable because one cannot observe u. We repeat there is no way to empirically test whether a variable is correlated with the regression error term because the error term is unobservable. Consequently, there is no way to to statistically ensure that an endogeneity problem has been solved.

> Outside of controlled experiments, there is no way to guarantee that endogneity problems are eliminated or sufficiently mitigated to ensure proper inferences. Ultimately, appropriately addressing endogeneity rests on the strength of one’s arguments supporting the identification strategy. To this end, we have stressed the importance of clearly discussing the relevant endogeneity concern — its causes and consequences — and how the proposed identification strategy addresses this issue. Only with clear and compelling arguments and analysis can one overcome endogeneity problems in observational studies.

## Several sources of endogeneity in model : 

### Ommited variables


> Omitted variables refer to those variables that should be included in the vector of explanatory variables, but for various reasons are not... The inability to observe these determinants means that instead of appearing among the explanatory variables, X, these omitted variables appear in the error term, u. If these omitted variables are uncorrelated with the included explanatory variables, then there is no problem for inference; the estimated coefficients are consistent and, under the stronger assumption of zero conditional mean, unbiased. If the two sets of variables are correlated, then there is an endogeneity problem that causes inference to break down.

### Simultaneity bias 

> It occurs when y and one or more of the x’s are determined in equilibrium so that it can plausibly be argued either that xk causes y or that y causes xk... unlike omitted variables bias, simultaneity bias is difficult to sign because it depends on the relative magnitudes of different effects, which cannot be known a priori.

I should be worried about simultaneity bias in my model as literature have shown that CFP influences CEP and inversely ?

### Measurement Error

> Most empirical studies in corporate finance use proxies for unobservable or difficult to quantify variables. Any discrepancy between the true variable of interest and the proxy leads to measurement error. These discrepancies arise not only because data collectors record variables incorrectly but also because of conceptual differences between proxies and their unobservable counterparts. When variables are measured imperfectly, the measurement error becomes part of the regression error. The impact of this error on coefficient estimates, not surprisingly, depends crucially on its statistical properties.

I need to show evidence that ROA, ROE and ROA are good proxy for CFP. 

## Identifying and Discussing the Endogeneity Problem

> Before discussing how to address endogeneity problems, we want to emphasize a more practical matter. A necessary first step in any empirical corporate finance study focused on disentangling alternative hypotheses or identifying causal effects is identifying the endogeneity problem and its implications for inference. Unsurprisingly, it is difficult, if not impossible, to address a problem without first understanding it. As such, we encourage researchers to discuss the primary endogeneity concern in their study. There are a number of questions that should be answered before putting forth a solution. Specifically, what is the endogenous variable(s)? Why are they endogenous? What are the implications for inferences of the endogeneity problems? In other words, what are the alternative hypotheses about which one should be concerned? Only after answering these questions can researchers put forth a solution to the endogeneity problem.


## Lagged Instruments as Instrument variables

> In general, we recommend thinking carefully about the economic justification for using lagged instruments. To our knowledge, no such justification has been put forth in corporate finance outside the Euler equation estimation literature. Rather, valid instruments for determinants of corporate behavior are more likely to come from institutional changes and nonfinancial variables.

> Unfortunately, it is often the case that in corporate finance more than one regressor is endogenous. In this case, inference about all of the regression coefficients can be compromised if one can find instruments for only a subset of the endogenous variables.

## Panel data Model 

> one of the most common causes of endogeneity in empirical corporate finance is omitted variables, and omitted variables are a problem because of the considerable heterogeneity present in many empirical corporate finance settings. Panel data can sometimes offer a partial, but by no means complete and costless, solution to this problem.

> Should a researcher always run Eqn (54) instead of Eqn (53) if panel data are available? The answer is not obvious. First, one should always try both specifications and check for statistical significance with a standard Hausman test in which the null is random effects and the alternative is fixed effects. However, one should also check to see whether the inclusion of fixed effects changes the coefficient magnitudes in an economically meaningful way. The reason is that including fixed effects reduces efficiency. Therefore, even if a Hausman test rejects the null of random effects, if the economic significance is little changed, the qualitative inferences from using pooled OLS on Eqn (53) can still be valid.

> In conclusion, fixed effects can ameliorate endogeneity concerns, but, as is the case with all econometric techniques, they should be used only after thinking carefully about the economic forces that might cause fixed effects to be an issue in the first place. Relatedly, fixed effects cannot remedy any arbitrary endogeneity problem and are by no means an endogeneity panacea. Indeed, they do nothing to address endogeneity associated with correlation between xit and eit. Further, in some instances fixed effects eliminate the most interesting or important variation researchers wish to explain. Examples in which fixed effects play a prominent role in identification include Khwaja and Mian (2008) and Hortacsu et al. (2010).