---
output : pdf_document
---

```{r include = FALSE}
knitr :: opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE, results = 'asis', tidy = TRUE)
```


```{r}
#############################################################
#############################################################
############## Package and DataBase loading #################
#############################################################
#############################################################

rm(list=ls()) #Removes all items in the environment!

#Packages
if (!require("utils")) install.packages("utils")
if (!require("dplyr")) install.packages("dplyr")
if (!require("plm")) install.packages("plm")
if (!require("stargazer")) install.packages("stargazer")
if (!require("xtable")) install.packages("xtable")
if (!require("data.table")) install.packages("data.table")

library(stargazer) # to create wonderful tables
library(plm) #to carry out regression
library(utils) #to write database in my folders
library(dplyr) #to play with data
library(data.table)
library(xtable)

#Database
DbLag1 <-as.data.frame(read.csv("DataBase/DataSynchronization/Lag2.csv", stringsAsFactors=FALSE, header = TRUE))

Model <- DbLag1 %>% select(c("CompaniesIndex",
                 "YearIndex",
                 "Ra",
                 "Roa",
                 "Roe",
                 "TobinsQ",
                 "AlphaJensen",
                 "Roic",
                 "GreenScore",
                 "CarbonProductivity",
                 "WaterProductivity",
                 "WasteProductivity",
                 "EnergyProductivity",
                 "SustainabilityPayLink",
                 "SustainableThemedCommitment",
                 "AuditScore",
                 "TotalAssets",
                 "DebtToEquityRatio",
                 "NetMargin",
                 "GicsClassification",
                 "Beta",
                 "CostEquity"
                 )) 

# I make some little changes
Model$FirmSize <- log(Model$TotalAssets)
Model$LogTobinsQ <- log(Model$TobinsQ)
setnames(Model, old = c("DebtToEquityRatio", "GicsClassification"), new = c("Leverage","Industry"))

```




```{r}

#####################################
####### 1// Remove Outliers #########
#####################################

# I define my models in lm as cooks.distance do not support plm object
Roa <-lm(Roa ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  + YearIndex , data = Model)

TobinsQ<-lm(log(TobinsQ) ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

Roe <- lm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

Roic <- lm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

Ra <- lm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)

AlphaJensen <- lm(AlphaJensen ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry  , data = Model)


## I calculate my cooks distance (i.e. D)
cooksdRoa <- cooks.distance(Roa)
cooksdTobinsQ <- cooks.distance(TobinsQ)
cooksdRoe <- cooks.distance(Roe)
cooksdRoic <- cooks.distance(Roic)
cooksdRa <- cooks.distance(Ra)
cooksdAlphaJensen <- cooks.distance(AlphaJensen)


## I extract rows considered as influential (observations whose D > 4 * means)

influentialRoa <- as.numeric(names(cooksdRoa)[(cooksdRoa > 4*mean(cooksdRoa, na.rm=T))])  
influentialTobin <- as.numeric(names(cooksdTobinsQ)[(cooksdTobinsQ > 4*mean(cooksdTobinsQ, na.rm=T))])  
influentialRoe <- as.numeric(names(cooksdRoe)[(cooksdRoe > 4*mean(cooksdRoe, na.rm=T))])  
influentialRoic <- as.numeric(names(cooksdRoic)[(cooksdRoic > 4*mean(cooksdRoic, na.rm=T))])  
influentialRa <- as.numeric(names(cooksdRa)[(cooksdRa > 4*mean(cooksdRa, na.rm=T))])  
influentialAlphaJensen <- as.numeric(names(cooksdAlphaJensen)[(cooksdAlphaJensen > 4*mean(cooksdAlphaJensen, na.rm=T))])


head(Model[influentialRoa, ])  # influential observations 
head(Model[influentialTobin, ])  # influential observations 
head(Model[influentialRoe, ])  # influential observations 
head(Model[influentialRoic, ])  # influential observations 
head(Model[influentialRa, ])  # influential observations 
head(Model[influentialAlphaJensen, ])  # influential observations 

#I remove outliers and create four new data frames that I write in my folders

TobinsQ_Db <- Model[-c(influentialTobin),]
write.csv(TobinsQ_Db, file = "DataBase/DataSynchronization/NoOutliersLag2/TobinsQ.csv")

Roa_Db <- Model[-c(influentialRoa),]
write.csv(Roa_Db, file = "DataBase/DataSynchronization/NoOutliersLag2/Roa.csv")

Roe_Db <- Model[-c(influentialRoe),]
write.csv(Roe_Db, file = "DataBase/DataSynchronization/NoOutliersLag2/Roe.csv")

Roic_Db <- Model[-c(influentialRoic),]
write.csv(Roic_Db, file = "DataBase/DataSynchronization/NoOutliersLag2/Roic.csv")

Ra_Db <- Model[-c(influentialRa),]
write.csv(Ra_Db, file = "DataBase/DataSynchronization/NoOutliersLag2/Ra.csv")

AlphaJensen_Db <- Model[-c(influentialAlphaJensen),]
write.csv(AlphaJensen_Db, file = "DataBase/DataSynchronization/NoOutliersLag2/AlphaJensen.csv")
```






```{r}

#########################################################
##################### Plm Test ##########################
#########################################################

# See [@Park2011] , [@Torres-Reyna2010], [@Croissant2008], [@Bell2016b], [@Baltagi2008] for interprations

# I make my database pdataframe

TobinsQ_Db <- pdata.frame(TobinsQ_Db, index = c("CompaniesIndex","YearIndex"))
Roa_Db <- pdata.frame(Roa_Db, index = c("CompaniesIndex","YearIndex"))
Roe_Db <- pdata.frame(Roe_Db, index = c("CompaniesIndex","YearIndex"))
Roic_Db <- pdata.frame(Roic_Db, index = c("CompaniesIndex","YearIndex"))
Ra_Db <- pdata.frame(Ra_Db, index = c("CompaniesIndex","YearIndex"))
AlphaJensen_Db <- pdata.frame(AlphaJensen_Db, index = c("CompaniesIndex","YearIndex"))


#######################################################
# A) LM test for random effects versus OLS
#######################################################

#TobinsQ
  PoolTobinsQ<- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))

  PlmtestTobinsQ <- cbind("TobinsQ", round(plmtest(PoolTobinsQ, effect = "time", type = "bp")$p.value, digits = 4), round(plmtest(PoolTobinsQ, effect = "individual", type = "bp")$p.value, digits = 4), round(plmtest(PoolTobinsQ, effect = "twoways", type = "bp")$p.value, digits = 4)) 
  
#Roa
  PoolRoa <- plm(Roa ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roa_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestRoa <- cbind("Roa", round(plmtest(PoolRoa, effect = "time", type = "bp")$p.value, digits = 4), round(plmtest(PoolRoa, effect = "individual", type = "bp")$p.value, digits = 4), round(plmtest(PoolRoa, effect = "twoways", type = "bp")$p.value, digits = 4))

#Roe
  PoolRoe<- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
    PlmtestRoe <- cbind("Roe", round(plmtest(PoolRoe, effect = "time", type = "bp")$p.value, digits = 4), round(plmtest(PoolRoe, effect = "individual", type = "bp")$p.value, digits = 4), round(plmtest(PoolRoe, effect = "twoways", type = "bp")$p.value, digits = 4))

#Roic
  PoolRoic <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roic_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestRoic <- cbind("Roic", round(plmtest(PoolRoic, effect = "time", type = "bp")$p.value, digits = 4 ),  round(plmtest(PoolRoic, effect = "individual", type = "bp")$p.value, digits = 4 ), round(plmtest(PoolRoic, effect = "twoways", type = "bp")$p.value, digits = 4))

#Ra
  PoolRa <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestRa <- cbind("Ra", round(plmtest(PoolRa, effect = "time", type = "bp")$p.value, digits = 4 ),  round(plmtest(PoolRa, effect = "individual", type = "bp")$p.value, digits = 4 ), round(plmtest(PoolRa, effect = "twoways", type = "bp")$p.value, digits = 4))

#AlphaJensen
  PoolAlphaJensen <- plm(AlphaJensen ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = AlphaJensen_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestAlphaJensen <- cbind("AlphaJensen", round(plmtest(PoolAlphaJensen, effect = "time", type = "bp")$p.value, digits = 4 ),  round(plmtest(PoolAlphaJensen, effect = "individual", type = "bp")$p.value, digits = 4 ), round(plmtest(PoolAlphaJensen, effect = "twoways", type = "bp")$p.value, digits = 4))
  
  
  
#Summary in a table    
      
  PlmTable <- as.data.frame(rbind(PlmtestTobinsQ, PlmtestRoa, PlmtestRoe, PlmtestRoic, PlmtestRa, PlmtestAlphaJensen))
  colnames(PlmTable) <- c("DependentVariables", "TimeEffect", "IndividualEffect", "TwowaysEffect")
  rownames(PlmTable) <- c()
  PlmTable[,2] <- as.numeric(as.character(PlmTable[,2]))  
  PlmTable[,3] <- as.numeric(as.character(PlmTable[,3]))  
  PlmTable[,4] <- as.numeric(as.character(PlmTable[,4]))  
  
  # Improve p-value understanding
  PlmTable$TimeEffect<-ifelse(PlmTable$TimeEffect<0.01,"< .01 ***",
		ifelse(PlmTable$TimeEffect<0.05,"< .05 **",
		ifelse(PlmTable$TimeEffect<0.1,"< .1 *",PlmTable$TimeEffect)))
  
  PlmTable$IndividualEffect<-ifelse(PlmTable$IndividualEffect<0.01,"< .01 ***",
		ifelse(PlmTable$IndividualEffect<0.05,"< .05 **",
		ifelse(PlmTable$IndividualEffect<0.1,"< .1 *",PlmTable$IndividualEffect)))     

  PlmTable$TwowaysEffect<-ifelse(PlmTable$TwowaysEffect<0.01,"< .01 ***",
		ifelse(PlmTable$TwowaysEffect<0.05,"< .05 **",
		ifelse(PlmTable$TwowaysEffect<0.1,"< .1 *",PlmTable$TwowaysEffect))) 
  
  #Xtable
  PlmTable1 <- xtable(PlmTable, caption = "Lagrange Multipliers test for random effects versus OLS", label = "Breusch", align = "lllll")
  
  print.xtable(PlmTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))


  
  
#######################################################
# B) F test for Random effects versus OLS

#The argument of this function is whether a plms object or two plm objects, the first being a within model, the second a pooling model. The effects tested are whether individual, time or twoways effects depending on the effects introduced in the model.
#######################################################
  
  # Time Effect
  ###################
  
  FixedTobinsQ<- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  FixedRoa<- plm(Roa ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roa_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedRoe<- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedRoic <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roic_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  FixedRa <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")


  FixedAlphaJensen <- plm(AlphaJensen ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = AlphaJensen_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  # Individual Effect
  ###################
  
  FixedTobinsQ1 <- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")
  
  FixedRoa1 <- plm(Roa ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roa_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")

  FixedRoe1 <- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")

  FixedRoic1 <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roic_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")
  
  FixedRa1 <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")

  FixedAlphaJensen1 <- plm(AlphaJensen ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = AlphaJensen_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "individual")
  
  # TwoWays Effect
  ###################
  
  FixedTobinsQ2 <- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")
  
  FixedRoa2 <- plm(Roa ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roa_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")

  FixedRoe2 <- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")

  FixedRoic2 <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roic_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")
  
  FixedRa2 <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")

  FixedAlphaJensen2 <- plm(AlphaJensen ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = AlphaJensen_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "twoways")
  
  #PfTest
  pFtestTobinsQ <- cbind("TobinsQ", round(pFtest(FixedTobinsQ, PoolTobinsQ, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedTobinsQ1, PoolTobinsQ, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedTobinsQ2, PoolTobinsQ, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestRoa <- cbind("Roa", round(pFtest(FixedRoa, PoolRoa, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedRoa1, PoolRoa, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedRoa2, PoolRoa, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestRoe <- cbind("Roe", round(pFtest(FixedRoe, PoolRoe, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedRoe1, PoolRoe, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedRoe2, PoolRoe, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestRoic <- cbind("Roic", round(pFtest(FixedRoic, PoolRoic, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedRoic1, PoolRoic, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedRoic2, PoolRoic, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestRa <- cbind("Ra", round(pFtest(FixedRa, PoolRa, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedRa1, PoolRa, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedRa2, PoolRa, effect = "twoways")$p.value, digits = 4 ))
  
  pFtestAlphaJensen <- cbind("AlphaJensen", round(pFtest(FixedAlphaJensen, PoolAlphaJensen, effect = "time")$p.value, digits = 4 ),round(pFtest(FixedAlphaJensen1, PoolAlphaJensen, effect = "individual")$p.value, digits = 4 ), round(pFtest(FixedAlphaJensen2, PoolAlphaJensen, effect = "twoways")$p.value, digits = 4 ))

#Summary in a table    
      
  pFtestTable <- as.data.frame(rbind(pFtestTobinsQ, pFtestRoa, pFtestRoe, pFtestRoic, pFtestRa, pFtestAlphaJensen))
  colnames(pFtestTable) <- c("DependentVariables", "TimeEffect", "IndividualEffect", "TwowaysEffect")
  rownames(pFtestTable) <- c()
  pFtestTable[,2] <- as.numeric(as.character(pFtestTable[,2]))  
  pFtestTable[,3] <- as.numeric(as.character(pFtestTable[,3]))  
  pFtestTable[,4] <- as.numeric(as.character(pFtestTable[,4]))  
  
  # Improve p-value understanding
  pFtestTable$TimeEffect<-ifelse(pFtestTable$TimeEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$TimeEffect<0.05,"< .05 **",
		ifelse(pFtestTable$TimeEffect<0.1,"< .1 *",pFtestTable$TimeEffect)))
  
  pFtestTable$IndividualEffect<-ifelse(pFtestTable$IndividualEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$IndividualEffect<0.05,"< .05 **",
		ifelse(pFtestTable$IndividualEffect<0.1,"< .1 *",pFtestTable$IndividualEffect)))     

  pFtestTable$TwowaysEffect<-ifelse(pFtestTable$TwowaysEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$TwowaysEffect<0.05,"< .05 **",
		ifelse(pFtestTable$TwowaysEffect<0.1,"< .1 *",pFtestTable$TwowaysEffect))) 
  
  #Xtable
  pFtestTable1 <- xtable(pFtestTable, caption = "F test for fixed effects versus OLS", label = "pFtest", align = "lllll")
  
  print.xtable(pFtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))


  
  
#######################################################
# C) Hausman Test
# phtest computes the Hausman test which is based on the comparison of two sets of estimates (see Hausman 1978). Its main arguments are two panelmodel objects or a formula. A classical application of the Hausman test for panel data is to compare the Random and the random effects models. 
#######################################################

  RandomTobinsQ<- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="random", index = c("CompaniesIndex","YearIndex"))
  
  RandomRoa<- plm(Roa ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roa_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomRoe<- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomRoic <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Roic_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomRa <- plm(Ra ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="random", index = c("CompaniesIndex","YearIndex"))
  
  RandomAlphaJensen <- plm(AlphaJensen ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = AlphaJensen_Db, model="random", index = c("CompaniesIndex","YearIndex"))

### Hausman test with time fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ, RandomTobinsQ)$p.value, digits = 4 ))
  phtestRoa <- cbind("Roa", round(phtest(FixedRoa, RandomRoa)$p.value, digits = 4 ))
  phtestRoe <- cbind("Roe", round(phtest(FixedRoe, RandomRoe)$p.value, digits = 4 ))
  phtestRoic <- cbind("Roic", round(phtest(FixedRoic, RandomRoic)$p.value, digits = 4 ))
  phtestRa <- cbind("Ra", round(phtest(FixedRa, RandomRa)$p.value, digits = 4 ))
  phtestAlphaJensen <- cbind("AlphaJensen", round(phtest(FixedAlphaJensen, RandomAlphaJensen)$p.value, digits = 4 ))
  


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestRoa, phtestRoe, phtestRoic, phtestRa, phtestAlphaJensen))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with time effect in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))


### Hausman test with indivudals fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ1, RandomTobinsQ)$p.value, digits = 4 ))
  phtestRoa <- cbind("Roa", round(phtest(FixedRoa1, RandomRoa)$p.value, digits = 4 ))
  phtestRoe <- cbind("Roe", round(phtest(FixedRoe1, RandomRoe)$p.value, digits = 4 ))
  phtestRoic <- cbind("Roic", round(phtest(FixedRoic1, RandomRoic)$p.value, digits = 4 ))
  phtestRa <- cbind("Ra", round(phtest(FixedRa1, RandomRa)$p.value, digits = 4 ))
  phtestAlphaJensen <- cbind("AlphaJensen", round(phtest(FixedAlphaJensen1, RandomAlphaJensen)$p.value, digits = 4 ))


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestRoa, phtestRoe, phtestRoic, phtestRa, phtestAlphaJensen))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with individual effect in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))
  
### Hausman test with twoways fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ2, RandomTobinsQ)$p.value, digits = 4 ))
  phtestRoa <- cbind("Roa", round(phtest(FixedRoa2, RandomRoa)$p.value, digits = 4 ))
  phtestRoe <- cbind("Roe", round(phtest(FixedRoe2, RandomRoe)$p.value, digits = 4 ))
  phtestRoic <- cbind("Roic", round(phtest(FixedRoic2, RandomRoic)$p.value, digits = 4 ))
  phtestRa <- cbind("Ra", round(phtest(FixedRa2, RandomRa)$p.value, digits = 4 ))
  phtestAlphaJensen <- cbind("AlphaJensen", round(phtest(FixedAlphaJensen2, RandomAlphaJensen)$p.value, digits = 4 ))


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestRoa, phtestRoe, phtestRoic, phtestRa, phtestAlphaJensen))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with twoways effects in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,6))
  
  
  
  
  
  
```
  

  
```{r}

####################################################################################
####################################################################################
########################## Regression Analysis Reporting ###########################
####################################################################################
####################################################################################

# TobinsQ
stargazer(PoolTobinsQ, RandomTobinsQ, summary = FALSE, title = "Model comparison TobinsQ - Pool (1), Random (2)", label = "TobinsQ", header = FALSE)

stargazer(FixedTobinsQ, FixedTobinsQ1, FixedTobinsQ2, summary = FALSE, title = "Model comparison TobinsQ - Fixed with time (1), individual (2) and twoways effects (3)", label = "TobinsQ1", header = FALSE)

# Roa
stargazer(PoolRoa, RandomRoa, summary = FALSE, title = "Model comparison Roa - Pool (1), Random (2)", label = "Roa", header = FALSE)

stargazer(FixedRoa, FixedRoa1, FixedRoa2, summary = FALSE, title = "Model comparison Roa - Fixed with time (1), individual (2) and twoways effects (3)", label = "Roa1", header = FALSE)

#Roe
stargazer(PoolRoe, RandomRoe, summary = FALSE, title = "Model comparison Roe - Pool (1), Random (2)", label = "Roe", header = FALSE)

stargazer(FixedRoe, FixedRoe1, FixedRoe2, summary = FALSE, title = "Model comparison Roe - Fixed with time (1), individual (2) and twoways effects (3)", label = "Roe1", header = FALSE)

#Roic
stargazer(PoolRoic, RandomRoic, summary = FALSE, title = "Model comparison Roic - Pool (1), Random (2)", label = "Roic", header = FALSE)

stargazer(FixedRoic, FixedRoic1, FixedRoic2, summary = FALSE, title = "Model comparison Roic - Fixed with time (1), individual (2) and twoways effects (3)", label = "Roic1", header = FALSE)

#Ra
stargazer(PoolRa, RandomRa, summary = FALSE, title = "Model comparison Ra - Pool (1), Random (2)", label = "Ra", header = FALSE)

stargazer(FixedRa, FixedRa1, FixedRa2, summary = FALSE, title = "Model comparison Ra - Fixed with time (1), individual (2) and twoways effects (3)", label = "Ra1", header = FALSE)

#AlphaJensen
stargazer(PoolAlphaJensen, RandomAlphaJensen, summary = FALSE, title = "Model comparison AlphaJensen - Pool (1), Random (2)", label = "AlphaJensen", header = FALSE)

stargazer(FixedAlphaJensen, FixedAlphaJensen1, FixedAlphaJensen2, summary = FALSE, title = "Model comparison AlphaJensen - Fixed with time (1), individual (2) and twoways effects (3)", label = "AlphaJensen1", header = FALSE)



# Based on test, I have to use pooling for both Tobin and Roe and fixed effect for both Roa and Roic. 

stargazer(FixedRoa, PoolRoe, summary = FALSE, header= FALSE, label = "summary", title = "Model based on LM, wild and hausmand test")

stargazer(PoolTobinsQ, FixedRoic, summary = FALSE, header= FALSE, label = "summary", title = "Model based on LM, wild and hausmand test")

```
  
  
  
  
  
```{r}


################################################################################
################################################################################
##################### Green Score :))))))       ################################
################################################################################
################################################################################



###################################
# Remove Outliers
###################################

TobinsQ <- lm(LogTobinsQ ~ GreenScore + FirmSize + Leverage + Industry + NetMargin, data = Model)
Roa <- lm(Roa ~ GreenScore + FirmSize + Leverage + Industry + NetMargin, data = Model)
Roe <- lm(Roe ~ GreenScore + FirmSize + Leverage + Industry + NetMargin, data = Model)
Ra <- lm(LogTobinsQ ~ GreenScore + FirmSize + Leverage + Industry + NetMargin, data = Model)

cooksdRoa <- cooks.distance(Roa)
cooksdTobinsQ <- cooks.distance(TobinsQ)
cooksdRoe <- cooks.distance(Roe)
cooksdRa <- cooks.distance(Ra)

## I extract rows considered as influential (observations whose D > 4 * means)

influentialRoa <- as.numeric(names(cooksdRoa)[(cooksdRoa > 4*mean(cooksdRoa, na.rm=T))])  
influentialTobin <- as.numeric(names(cooksdTobinsQ)[(cooksdTobinsQ > 4*mean(cooksdTobinsQ, na.rm=T))])  
influentialRoe <- as.numeric(names(cooksdRoe)[(cooksdRoe > 4*mean(cooksdRoe, na.rm=T))])  
influentialRa <- as.numeric(names(cooksdRa)[(cooksdRa > 4*mean(cooksdRa, na.rm=T))])  



head(Model[influentialRoa, ])  # influential observations 
head(Model[influentialTobin, ])  # influential observations 
head(Model[influentialRoe, ])  # influential observations 
head(Model[influentialRa, ])  # influential observations 


#I remove outliers and create four new data frames that I write in my folders

TobinsQ_Db <- Model[-c(influentialTobin),]
write.csv(TobinsQ_Db, file = "DataBase/DataSynchronization/NoOutliersLag1/GreenScore/TobinsQ.csv")

Roa_Db <- Model[-c(influentialRoa),]
write.csv(Roa_Db, file = "DataBase/DataSynchronization/NoOutliersLag1/GreenScore/Roa.csv")

Roe_Db <- Model[-c(influentialRoe),]
write.csv(Roe_Db, file = "DataBase/DataSynchronization/NoOutliersLag1/GreenScore/Roe.csv")

Ra_Db <- Model[-c(influentialRa),]
write.csv(Roe_Db, file = "DataBase/DataSynchronization/NoOutliersLag1/GreenScore/Ra.csv")



# I make my database pdataframe

TobinsQ_Db <- pdata.frame(TobinsQ_Db, index = c("CompaniesIndex","YearIndex"))
Roa_Db <- pdata.frame(Roa_Db, index = c("CompaniesIndex","YearIndex"))
Roe_Db <- pdata.frame(Roe_Db, index = c("CompaniesIndex","YearIndex"))
Ra_Db <- pdata.frame(Ra_Db, index = c("CompaniesIndex","YearIndex"))



#######################################################
# A) LM test for random effects versus OLS
#######################################################

#TobinsQ
  PoolTobinsQ<- plm(LogTobinsQ ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))

  PlmtestTobinsQ <- cbind("TobinsQ", round(plmtest(PoolTobinsQ, effect = "time", type = "bp")$p.value, digits = 4))
  
#Roa
  PoolRoa <- plm(Roa ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Roa_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestRoa <- cbind("Roa", round(plmtest(PoolRoa, effect = "time", type = "bp")$p.value, digits = 4))
#Roe
  PoolRoe<- plm(Roe ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
    PlmtestRoe <- cbind("Roe", round(plmtest(PoolRoe, effect = "time", type = "bp")$p.value, digits = 4))

#Ra
  PoolRa <- plm(Ra ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="pooling", index = c("CompaniesIndex","YearIndex"))
  
  PlmtestRa <- cbind("Ra", round(plmtest(PoolRa, effect = "time", type = "bp")$p.value, digits = 4 ))


#Summary in a table    
      
  PlmTable <- as.data.frame(rbind(PlmtestTobinsQ, PlmtestRoa, PlmtestRoe, PlmtestRa))
  colnames(PlmTable) <- c("DependentVariables", "TimeEffect")
  rownames(PlmTable) <- c()
  PlmTable[,2] <- as.numeric(as.character(PlmTable[,2]))  

  # Improve p-value understanding
  PlmTable$TimeEffect<-ifelse(PlmTable$TimeEffect<0.01,"< .01 ***",
		ifelse(PlmTable$TimeEffect<0.05,"< .05 **",
		ifelse(PlmTable$TimeEffect<0.1,"< .1 *",PlmTable$TimeEffect)))
 
 
  #Xtable
  PlmTable1 <- xtable(PlmTable, caption = "Lagrange Multipliers test for random effects versus OLS", label = "Breusch", align = "lll")
  
  print.xtable(PlmTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


#######################################################
# B) F / Wilrd test for Fixed effects versus OLS
#######################################################
  
  # Time Effect
  ###################
  
  FixedTobinsQ<- plm(LogTobinsQ ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")
  
  FixedRoa<- plm(Roa ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = Roa_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedRoe<- plm(Roe ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")

  FixedRa <- plm(Ra ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="within", index = c("CompaniesIndex","YearIndex"), effect = "time")



  #PfTest
  pFtestTobinsQ <- cbind("TobinsQ", round(pFtest(FixedTobinsQ, PoolTobinsQ, effect = "time")$p.value, digits = 4 ))
  
  pFtestRoa <- cbind("Roa", round(pFtest(FixedRoa, PoolRoa, effect = "time")$p.value, digits = 4 ))
  
  pFtestRoe <- cbind("Roe", round(pFtest(FixedRoe, PoolRoe, effect = "time")$p.value, digits = 4 ))
  
  pFtestRa <- cbind("Ra", round(pFtest(FixedRa, PoolRa, effect = "time")$p.value, digits = 4 ))
  

#Summary in a table    
      
  pFtestTable <- as.data.frame(rbind(pFtestTobinsQ, pFtestRoa, pFtestRoe, pFtestRa))
  colnames(pFtestTable) <- c("DependentVariables", "TimeEffect")
  rownames(pFtestTable) <- c()
  pFtestTable[,2] <- as.numeric(as.character(pFtestTable[,2]))  

  # Improve p-value understanding
  pFtestTable$TimeEffect<-ifelse(pFtestTable$TimeEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$TimeEffect<0.05,"< .05 **",
		ifelse(pFtestTable$TimeEffect<0.1,"< .1 *",pFtestTable$TimeEffect)))

  #Xtable
  pFtestTable1 <- xtable(pFtestTable, caption = "F test for fixed effects versus OLS", label = "pFtest", align = "lll")
  
  print.xtable(pFtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


#######################################################
# C) Hausman Test
#######################################################

  RandomTobinsQ<- plm(LogTobinsQ ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = TobinsQ_Db, model="random", index = c("CompaniesIndex","YearIndex"))
  
  RandomRoa<- plm(Roa ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Roa_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomRoe<- plm(Roe ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Roe_Db, model="random", index = c("CompaniesIndex","YearIndex"))

  RandomRa <- plm(Ra ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Ra_Db, model="random", index = c("CompaniesIndex","YearIndex"))



### Hausman test with time fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ, RandomTobinsQ)$p.value, digits = 4 ))
  phtestRoa <- cbind("Roa", round(phtest(FixedRoa, RandomRoa)$p.value, digits = 4 ))
  phtestRoe <- cbind("Roe", round(phtest(FixedRoe, RandomRoe)$p.value, digits = 4 ))
  phtestRa <- cbind("Ra", round(phtest(FixedRa, RandomRa)$p.value, digits = 4 ))

  


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestRoa, phtestRoe, phtestRa))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with time effect in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


#######################################################
# D) Result Reporting
#######################################################
  
stargazer(PoolTobinsQ, PoolRoe, summary = FALSE, title = "Pool Model", label = "GreenScore", header = FALSE)
stargazer(FixedRoa, RandomRa, summary = FALSE, title = "Fixed and Random Model", label = "GreenScore", header = FALSE)

  
```
  
  
  







