---
output : pdf_document
---

```{r include = FALSE}
knitr :: opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE, results = 'asis', tidy = TRUE)
```


```{r}
#############################################################
#############################################################
############## Package and DataBase loading #################
#############################################################
#############################################################

rm(list=ls()) #Removes all items in the environment!

#Packages
if (!require("utils")) install.packages("utils")
if (!require("dplyr")) install.packages("dplyr")
if (!require("plm")) install.packages("plm")
if (!require("stargazer")) install.packages("stargazer")
if (!require("xtable")) install.packages("xtable")
if (!require("data.table")) install.packages("data.table")

library(stargazer) # to create wonderful tables
library(plm) #to carry out regression
library(utils) #to write database in my folders
library(dplyr) #to play with data
library(data.table)
library(xtable)

#Database
DbLag1 <-as.data.frame(read.csv("DataBase/DataSynchronization/Lag0.csv", stringsAsFactors=FALSE, header = TRUE))

Model <- DbLag1 %>% select(c("Index",
                 "Year",
                 "Ra",
                 "Roa",
                 "Roe",
                 "TobinsQ",
                 "AlphaJensen",
                 "Roic",
                 "GreenScore",
                 "CarbonProductivity",
                 "WaterProductivity",
                 "WasteProductivity",
                 "EnergyProductivity",
                 "SustainabilityPayLink",
                 "SustainableThemedCommitment",
                 "AuditScore",
                 "TotalAssets",
                 "DebtToEquityRatio",
                 "NetMargin",
                 "GicsClassification",
                 "Beta",
                 "CostEquity"
                 )) 

# I make some little changes
Model$FirmSize <- log(Model$TotalAssets)
Model$LogTobinsQ <- log(Model$TobinsQ)
setnames(Model, old = c("DebtToEquityRatio", "GicsClassification"), new = c("Leverage","Industry"))

```





```{r}

#########################################################
##################### Plm Test ##########################
#########################################################

# See [@Park2011] , [@Torres-Reyna2010], [@Croissant2008], [@Bell2016b], [@Baltagi2008] for interprations

# I make my database pdataframe

Model <- pdata.frame(Model, index = c("Index","Year"))



#######################################################
# A) LM test for random effects versus OLS
#######################################################

#TobinsQ
  PoolTobinsQ<- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="pooling", index = c("Index","Year"))

  PlmtestTobinsQ <- cbind("TobinsQ", round(plmtest(PoolTobinsQ, effect = "time", type = "bp")$p.value, digits = 4))
  
#Roa
  PoolRoa <- plm(Roa ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="pooling", index = c("Index","Year"))
  
  PlmtestRoa <- cbind("Roa", round(plmtest(PoolRoa, effect = "time", type = "bp")$p.value, digits = 4))
#Roe
  PoolRoe<- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="pooling", index = c("Index","Year"))
  
    PlmtestRoe <- cbind("Roe", round(plmtest(PoolRoe, effect = "time", type = "bp")$p.value, digits = 4))

#Roic
  PoolRoic <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="pooling", index = c("Index","Year"))
  
  PlmtestRoic <- cbind("Roic", round(plmtest(PoolRoic, effect = "time", type = "bp")$p.value, digits = 4 ))

  
  
  
#Summary in a table    
      
  PlmTable <- as.data.frame(rbind(PlmtestTobinsQ, PlmtestRoa, PlmtestRoe, PlmtestRoic))
  colnames(PlmTable) <- c("DependentVariables", "TimeEffect")
  rownames(PlmTable) <- c()
  PlmTable[,2] <- as.numeric(as.character(PlmTable[,2]))  

  
  # Improve p-value understanding
  PlmTable$TimeEffect<-ifelse(PlmTable$TimeEffect<0.01,"< .01 ***",
		ifelse(PlmTable$TimeEffect<0.05,"< .05 **",
		ifelse(PlmTable$TimeEffect<0.1,"< .1 *",PlmTable$TimeEffect)))
  

  
  #Xtable
  PlmTable1 <- xtable(PlmTable, caption = "Lagrange Multipliers test for random effects versus OLS", label = "Breusch", align = "lll")
  
  print.xtable(PlmTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


  
  
#######################################################
# B) F test for Random effects versus OLS

#The argument of this function is whether a plms object or two plm objects, the first being a within model, the second a pooling model. The effects tested are whether individual, time or twoways effects depending on the effects introduced in the model.
#######################################################
  
  # Time Effect
  ###################
  
  FixedTobinsQ<- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="within", index = c("Index","Year"), effect = "time")
  
  FixedRoa<- plm(Roa ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="within", index = c("Index","Year"), effect = "time")

  FixedRoe<- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="within", index = c("Index","Year"), effect = "time")

  FixedRoic <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="within", index = c("Index","Year"), effect = "time")
  


  

  

  #PfTest
  pFtestTobinsQ <- cbind("TobinsQ", round(pFtest(FixedTobinsQ, PoolTobinsQ, effect = "time")$p.value, digits = 4 ))
  
  pFtestRoa <- cbind("Roa", round(pFtest(FixedRoa, PoolRoa, effect = "time")$p.value, digits = 4 ))
  
  pFtestRoe <- cbind("Roe", round(pFtest(FixedRoe, PoolRoe, effect = "time")$p.value, digits = 4 ))
  
  pFtestRoic <- cbind("Roic", round(pFtest(FixedRoic, PoolRoic, effect = "time")$p.value, digits = 4 ))
  

#Summary in a table    
      
  pFtestTable <- as.data.frame(rbind(pFtestTobinsQ, pFtestRoa, pFtestRoe, pFtestRoic))
  colnames(pFtestTable) <- c("DependentVariables", "TimeEffect")
  rownames(pFtestTable) <- c()
  pFtestTable[,2] <- as.numeric(as.character(pFtestTable[,2]))  

  
  # Improve p-value understanding
  pFtestTable$TimeEffect<-ifelse(pFtestTable$TimeEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$TimeEffect<0.05,"< .05 **",
		ifelse(pFtestTable$TimeEffect<0.1,"< .1 *",pFtestTable$TimeEffect)))
  
  #Xtable
  pFtestTable1 <- xtable(pFtestTable, caption = "F test for fixed effects versus OLS", label = "pFtest", align = "lll")
  
  print.xtable(pFtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


  
  
#######################################################
# C) Hausman Test
# phtest computes the Hausman test which is based on the comparison of two sets of estimates (see Hausman 1978). Its main arguments are two panelmodel objects or a formula. A classical application of the Hausman test for panel data is to compare the Random and the random effects models. 
#######################################################

  RandomTobinsQ<- plm(LogTobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="random", index = c("Index","Year"))
  
  RandomRoa<- plm(Roa ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="random", index = c("Index","Year"))

  RandomRoe<- plm(Roe ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="random", index = c("Index","Year"))

  RandomRoic <- plm(Roic ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + CarbonProductivity + WaterProductivity + WasteProductivity + FirmSize + NetMargin + Leverage + Industry , data = Model, model="random", index = c("Index","Year"))


### Hausman test with time fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ, RandomTobinsQ)$p.value, digits = 4 ))
  phtestRoa <- cbind("Roa", round(phtest(FixedRoa, RandomRoa)$p.value, digits = 4 ))
  phtestRoe <- cbind("Roe", round(phtest(FixedRoe, RandomRoe)$p.value, digits = 4 ))
  phtestRoic <- cbind("Roic", round(phtest(FixedRoic, RandomRoic)$p.value, digits = 4 ))

  


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestRoa, phtestRoe, phtestRoic))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with time effect in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))

  
```
  

  
```{r}

####################################################################################
####################################################################################
########################## Regression Analysis Reporting ###########################
####################################################################################
####################################################################################

# Based on test, I have to use pooling for both Tobin and Roe and fixed effect for both Roa and Roic. 

stargazer(FixedTobinsQ, summary = FALSE, header= FALSE, label = "summary", title = "Fixed  TobinsQ")

stargazer(PoolRoa, PoolRoe, PoolRoic, summary = FALSE, header= FALSE, label = "summary", title = "Pool Model")

```
  
  
  
  
  
```{r}


################################################################################
################################################################################
##################### Green Score :))))))       ################################
################################################################################
################################################################################


#######################################################
# A) LM test for random effects versus OLS
#######################################################

#TobinsQ
  PoolTobinsQ<- plm(LogTobinsQ ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Model, model="pooling", index = c("Index","Year"))

  PlmtestTobinsQ <- cbind("TobinsQ", round(plmtest(PoolTobinsQ, effect = "time", type = "bp")$p.value, digits = 4))
  
#Roa
  PoolRoa <- plm(Roa ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Model, model="pooling", index = c("Index","Year"))
  
  PlmtestRoa <- cbind("Roa", round(plmtest(PoolRoa, effect = "time", type = "bp")$p.value, digits = 4))
#Roe
  PoolRoe<- plm(Roe ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Model, model="pooling", index = c("Index","Year"))
  
    PlmtestRoe <- cbind("Roe", round(plmtest(PoolRoe, effect = "time", type = "bp")$p.value, digits = 4))

#Roic
  PoolRoic <- plm(Roic ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Model, model="pooling", index = c("Index","Year"))
  
  PlmtestRoic <- cbind("Roic", round(plmtest(PoolRoic, effect = "time", type = "bp")$p.value, digits = 4 ))


#Summary in a table    
      
  PlmTable <- as.data.frame(rbind(PlmtestTobinsQ, PlmtestRoa, PlmtestRoe, PlmtestRoic))
  colnames(PlmTable) <- c("DependentVariables", "TimeEffect")
  rownames(PlmTable) <- c()
  PlmTable[,2] <- as.numeric(as.character(PlmTable[,2]))  

  # Improve p-value understanding
  PlmTable$TimeEffect<-ifelse(PlmTable$TimeEffect<0.01,"< .01 ***",
		ifelse(PlmTable$TimeEffect<0.05,"< .05 **",
		ifelse(PlmTable$TimeEffect<0.1,"< .1 *",PlmTable$TimeEffect)))
 
 
  #Xtable
  PlmTable1 <- xtable(PlmTable, caption = "Lagrange Multipliers test for random effects versus OLS", label = "Breusch", align = "lll")
  
  print.xtable(PlmTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


#######################################################
# B) F / Wilrd test for Fixed effects versus OLS
#######################################################
  
  # Time Effect
  ###################
  
  FixedTobinsQ<- plm(LogTobinsQ ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = Model, model="within", index = c("Index","Year"), effect = "time")
  
  FixedRoa<- plm(Roa ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = Model, model="within", index = c("Index","Year"), effect = "time")

  FixedRoe<- plm(Roe ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = Model, model="within", index = c("Index","Year"), effect = "time")

  FixedRoic <- plm(Roic ~ GreenScore+ FirmSize + NetMargin + Leverage + Industry , data = Model, model="within", index = c("Index","Year"), effect = "time")



  #PfTest
  pFtestTobinsQ <- cbind("TobinsQ", round(pFtest(FixedTobinsQ, PoolTobinsQ, effect = "time")$p.value, digits = 4 ))
  
  pFtestRoa <- cbind("Roa", round(pFtest(FixedRoa, PoolRoa, effect = "time")$p.value, digits = 4 ))
  
  pFtestRoe <- cbind("Roe", round(pFtest(FixedRoe, PoolRoe, effect = "time")$p.value, digits = 4 ))
  
  pFtestRoic <- cbind("Roic", round(pFtest(FixedRoic, PoolRoic, effect = "time")$p.value, digits = 4 ))
  

#Summary in a table    
      
  pFtestTable <- as.data.frame(rbind(pFtestTobinsQ, pFtestRoa, pFtestRoe, pFtestRoic))
  colnames(pFtestTable) <- c("DependentVariables", "TimeEffect")
  rownames(pFtestTable) <- c()
  pFtestTable[,2] <- as.numeric(as.character(pFtestTable[,2]))  

  # Improve p-value understanding
  pFtestTable$TimeEffect<-ifelse(pFtestTable$TimeEffect<0.01,"< .01 ***",
		ifelse(pFtestTable$TimeEffect<0.05,"< .05 **",
		ifelse(pFtestTable$TimeEffect<0.1,"< .1 *",pFtestTable$TimeEffect)))

  #Xtable
  pFtestTable1 <- xtable(pFtestTable, caption = "F test for fixed effects versus OLS", label = "pFtest", align = "lll")
  
  print.xtable(pFtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


#######################################################
# C) Hausman Test
#######################################################

  RandomTobinsQ<- plm(LogTobinsQ ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Model, model="random", index = c("Index","Year"))
  
  RandomRoa<- plm(Roa ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Model, model="random", index = c("Index","Year"))

  RandomRoe<- plm(Roe ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Model, model="random", index = c("Index","Year"))

  RandomRoic <- plm(Roic ~ GreenScore + FirmSize + NetMargin + Leverage + Industry , data = Model, model="random", index = c("Index","Year"))



### Hausman test with time fixed model
  
  # Hausman Test
  phtestTobinsQ <- cbind("TobinsQ", round(phtest(FixedTobinsQ, RandomTobinsQ)$p.value, digits = 4 ))
  phtestRoa <- cbind("Roa", round(phtest(FixedRoa, RandomRoa)$p.value, digits = 4 ))
  phtestRoe <- cbind("Roe", round(phtest(FixedRoe, RandomRoe)$p.value, digits = 4 ))
  phtestRoic <- cbind("Roic", round(phtest(FixedRoic, RandomRoic)$p.value, digits = 4 ))

  


#Summary in a table    
      
  phtestTable <- as.data.frame(rbind(phtestTobinsQ, phtestRoa, phtestRoe, phtestRoic))
  colnames(phtestTable) <- c("DependentVariables", "pvalue")
  rownames(phtestTable) <- c()
  phtestTable[,2] <- as.numeric(as.character(phtestTable[,2]))  

  
  # Improve p-value understanding
  phtestTable$pvalue<-ifelse(phtestTable$pvalue<0.01,"< .01 ***",
		ifelse(phtestTable$pvalue<0.05,"< .05 **",
		ifelse(phtestTable$pvalue<0.1,"< .1 *",phtestTable$pvalue)))
  
  #Xtable
  phtestTable1 <- xtable(phtestTable, caption = "Hausman Test with time effect in fixed model", label = "Hausman", align = "lll")
  
  print.xtable(phtestTable1, type = "latex", table.placement = "h", caption.placement = "top", comment = FALSE, hline.after = c(-1,-1,0,4))


#######################################################
# D) Result Reporting
#######################################################
  
stargazer(FixedTobinsQ, summary = FALSE, header= FALSE, label = "summary", title = "Fixed  TobinsQ")

stargazer(PoolRoa, PoolRoe, PoolRoic, summary = FALSE, header= FALSE, label = "summary", title = "Pool Model")

  
```
  
  
  







