---
title: "EndogeneityTest"
author: "Kinif Pierrick"
date: "5 avril 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, results = 'asis')
```

```{r}
#Download package and database

if (!require("systemfit")) install.packages("systemfit")
library(systemfit)
if (!require("plm")) install.packages("plm")
library(plm)
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
if (!require("utils")) install.packages("utils")
library(utils)

# I dowload my database befor knitting
# The excel file contains several sheets with all my data
# The csv file contains only variables of my model. Hence I dowload my DB with read.csv2
DB_Roa_Lagged<-data.frame(read.csv2("DataBase/DataBase_010418.csv", sep = ";",stringsAsFactors=FALSE, header = TRUE ))
DB_Tobin_Lagged <- filter(DB_Roa_Lagged, !is.na(TobinsQ))

DB_Roa_NotLagged<-data.frame(read.csv2("DataBase/DB_Roa_NotLagged.csv", sep = ";",stringsAsFactors=FALSE, header = TRUE ))
DB_Tobin_NotLagged <- filter(DB_Roa_NotLagged, !is.na(TobinsQ))

## This DB will be used for analysis with my dependent variable = ROA

# From DB I select only row where TobinsQ <> zero . This database will be used when my dependent variable = TobinsQ

```


# Lag vs not Lag With outliers

```{r}
#Test Lag vs not lag

if (!require("stargazer")) install.packages("stargazer")
library(stargazer)

M5_Lagged <- plm(ROA ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Roa_Lagged, index = c("Companies", "YearFinancialIndicator"))

M6_Lagged <- plm(TobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Tobin_Lagged, index = c("Companies", "YearFinancialIndicator"))

M5_NotLagged <- plm(ROA ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Roa_NotLagged, index = c("Companies", "YearFinancialIndicator"))

M6_NotLagged <- plm(TobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Tobin_NotLagged, index = c("Companies", "YearFinancialIndicator"))

stargazer(M5_Lagged, M6_Lagged,  table.placement = "h", type="latex", label = "Plm", title = "Within Model M5 et M6 with one lag", header = FALSE)

stargazer(M5_NotLagged, M6_NotLagged, table.placement = "h", type="latex", label = "Plm", title = "Within Model M5 et M6 withoutlag", header = FALSE)



```


\newpage

# Lag vs not Lag With outliers Without Outliers


```{r echo = FALSE, message = FALSE, warning = FALSE, fig.align = 'center', fig.width = 6, fig.height = 6}
if (!require("utils")) install.packages("utils")
if (!require("car")) install.packages("car")
if (!require("dplyr")) install.packages("dplyr")

library(utils)
library(car)
library(dplyr)

#OutliersTest ne peut être appliquer sur des objets plm dont redo avec lm

M5_LaggedLm <- lm(ROA ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry, data = DB_Roa_Lagged)

M6_LaggedLm <- lm(TobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry, data = DB_Tobin_Lagged)

M5_NotLaggedLm <- lm(ROA ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry, data = DB_Roa_NotLagged)

M6_NotLaggedLm <- lm(TobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry, data = DB_Tobin_NotLagged)

#Mesure cooksdistance

cooksd_M5_NotLagged <- cooks.distance(M5_NotLaggedLm)
cooksd_M5_Lagged <- cooks.distance(M5_LaggedLm)
cooksd_M6_NotLagged <- cooks.distance(M6_NotLaggedLm)
cooksd_M6_Lagged <- cooks.distance(M6_LaggedLm)

Outliers_M5NotLagged <- car::outlierTest(M5_NotLaggedLm)
Outliers_M5Lagged <- car::outlierTest(M5_LaggedLm)
Outliers_M6Lagged <- car::outlierTest(M6_LaggedLm)
Outliers_M6NotLagged <- car::outlierTest(M6_NotLaggedLm)

#I remove outliers from database

DB_Roa_NotLagged_NoOutliers <- DB_Roa_NotLagged[-c(673,1057,922,483,1135,1122,563,10),]

DB_Roa_Lagged_NoOutliers <- DB_Roa_Lagged[-c(1167,96,384,483,1121,1170,482,1122,562),]

DB_Tobin_NotLagged_NoOutliers <- DB_Tobin_NotLagged  [-c(501,500,1000,1014,822,1013,611,821,388,61),]

DB_Tobin_Lagged_NoOutliers <- DB_Tobin_Lagged  [-c(498,497,496,996,1009,995,818,607,819),]

# I redo plm with new databes

M5_Lagged_NoOutliers <- plm(ROA ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Roa_Lagged_NoOutliers, index = c("Companies", "YearFinancialIndicator"))

M6_Lagged_NoOutliers <- plm(TobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Tobin_Lagged_NoOutliers, index = c("Companies", "YearFinancialIndicator"))

M5_NotLagged_NoOutliers <- plm(ROA ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Roa_NotLagged_NoOutliers, index = c("Companies", "YearFinancialIndicator"))

M6_NotLagged_NoOutliers <- plm(TobinsQ ~ SustainabilityPayLink + SustainableThemedCommitment + AuditScore + EnergyProductivity + CarbonProductivity + WaterProductivity + WasteProductivity + Leverage + NetMargin + FirmSize + Industry + factor(YearFinancialIndicator), model = "within", data = DB_Tobin_NotLagged_NoOutliers, index = c("Companies", "YearFinancialIndicator"))

stargazer(M5_Lagged_NoOutliers, M6_Lagged_NoOutliers,  table.placement = "h", type="latex", label = "Plm", title = "Within Model M5 et M6 with one lag and without outliers", header = FALSE)

stargazer(M5_NotLagged_NoOutliers, M6_NotLagged_NoOutliers, table.placement = "h", type="latex", label = "Plm", title = "Within Model M5 et M6 withoutlag and without outliers", header = FALSE)

```
