---
title: "DataBase Documentation"
author: "Kinif Pierrick"
date: "26 mars 2018"
output: pdf_document
---

This document give you an overview of my databases.



```{r warning = FALSE, message = FALSE}
rm(list=ls()) #Removes all items in Environment!
if (!require("utils")) install.packages("utils")
if (!require("dplyr")) install.packages("dplyr")
if (!require("plm")) install.packages("plm")

library(plm)
library(utils)
library(dplyr)

# The excel file contains several sheets with all my data
# The csv file contains only variables of my model. Hence I dowload my DB with read.csv2
DB_Roa<-data.frame(read.csv2("DataBase_010418.csv", sep = ";",stringsAsFactors=FALSE, header = TRUE ))
write.csv2(DB_Roa, file = "DB_Roa.csv")
## This DB will be used for analysis with my dependent variable = ROA

# From DB I select only row where TobinsQ <> zero . This database will be used when my dependent variable = TobinsQ

DB_Tobin <- filter(DB_Roa, !is.na(TobinsQ))
write.csv2(DB_Tobin, file = "DB_Tobin.csv")
```



The table \ref{Smpl} contains a sample of my database.


```{r echo = FALSE, message = FALSE, warning = FALSE,  results='asis'}
if (!require("stargazer")) install.packages("stargazer")
library(stargazer)

if (!require("plm")) install.packages("plm")
library(plm)

PanelData <- pdata.frame(DB_Roa, index=c("Companies", "YearFinancialIndicator"))
smpl <- PanelData[c(1:10),c(1:4)]
stargazer(PanelData[c(1:10),c(1:4)], summary = FALSE, type="latex", title = "Sample selection of the data base", label="Smpl", table.placement = "h", digits = 2, header = FALSE) # the agument 'header = FALSE" is really important to remove the citation info of stargazer package"

```



Function *pdim()* extracts the dimensions of the panel data:



```{r echo = TRUE}
library(plm)
pdim(DB_Roa)
pdim(DB_Tobin)
```





```{r}
#Create variable vector from column names
variables <- c("Tobin's Q",
               "Return on Asset",
               "Energy Productivity",
               "Carbon Productivity",
               "Water Productiviry",
               "Waste Productivity",
               "Green Reputation",
               "Sustainability Pay Link",
               "Sustainable Themed Commitment",
               "Audit Score",
               "Leverage",
               "Net Margin",
               "Firm Size",
               "Industry"
               )

#create variable vector from column names
DescriptionVariables <- c("The ratio of a firm’s market value to the replacement cost of its assets",
                          "Earnings before interest over total firm assets",
                          "")
```

