---
title: "Data Description"
author: "Kinif Pierrick"
date: "22 avril 2018"
output: pdf_document
---


# Overview

This document aims at giving you an overview of my DataBase folders. This one is split up into several sub-folders :

## CAPM

This sub-folders contains :

i. the Fama and French 3 Factors (ie. Risk Free Rate and Return Market) collecting from http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/index.html on 18th April 2018 and,
ii. The "CAPM.csv" file which is the output of the *MakeFile_Capm.rmd*. 

The second file contains several variables :

 	
* Ra :	Compounded returns (i.e. log (1+r) with r equals the monthly return of the stock
* Rf :	Rf = Risk Free Rate 
* Rm : The Market Return
* Beta :	Beta of the CAPM 
* AlphaJensen	: Jensen's Alpha which had been calculated using the CAMP 3 factors, namely : AlphaJensen = (Ra - Rf) - Beta * (Rm - Rf) 
* CostEquity :	Cost of Equity calculated with the CAPM as CostEquity = Rf + Beta * (Rm-Rf)

All data are on a monthly basis.

## StockPup

This sub-folders contains two csv files and are the output of the *MakeFile_StockPup.rmd* : 

i. *StkP_From2012.csv* which are data from 2012 (i.e. the fourth quartely) for all my companies. 
ii. *Stkp_From2012.csv* which are quartely data for all my companies and no restriction of times is applied. This is the full dataset of [StockPup](http://www.stockpup.com/data/).

Both files contain several variables : 

* Shares :	The total number of common shares outstanding at the end of a given quarter, including all classes of common stock.
* Shares split adjusted :	The number of shares the company had at the end of a given quarter, adjusted for splits to be comparable to today's shares.
* Split factor	: If an investor started with 1 share of stock at the end of a given quarter, the split factor for that quarter indicates how many shares the investor would own today as a result of subsequent stock splits.
* Current assets	: Current assets at the end of a quarter.
* Assets :	Total assets at the end of a quarter.
* Current liabilities :	Current liabilities at the end of a quarter.
* Liabilities :	Total liabilities at the end of a quarter.
* Shareholders equity :	Total shareholders' equity at the end of a quarter, including both common and preferred stockholders.
* Non-controlling interest :	Non-controlling or minority interest, if any, excluded from Shareholders equity.
* Preferred equity :	Preferred equity, if any, included in Shareholders equity.
* Goodwill & intangibles :	Total Goodwill and all other Intangible assets, if any.
* Long-term debt	: All long-term debt including capital lease obligations.
* Revenue	: Total revenue for a given quarter.
* Earnings :	Earnings or Net Income for a given quarter.
* Earnings available for common stockholders :	Earnings available for common stockholders - Net income minus earnings that must be distributed to preferred shareholders. May be omitted when not reported by the company.
* EPS basic	: Basic earnings per share for a given quarter.
* EPS diluted	: Diluted earnings per share.
* Dividend per share :	Common stock dividends paid during a quarter per share, including all regular and special dividends and distributions to common shareholders.
* Cash from operating activities :	Cash produced by operating activities during a given quarter, including Continuing and Discontinued operations.
* Cash from investing activities :	Cash produced by investing activities during a given quarter, including Continuing and Discontinued operations.
* Cash from financing activities :	Cash produced by financing activities during a given quarter, including Continuing and Discontinued operations.
* Cash change during period	: Change in cash and cash equivalents during a given quarter, including Effect of Exchange Rate Movements and Other Cash Change Adjustments, if any.
* Cash at end of period	: Cash and cash equivalents at the end of a quarter, including Continuing and Discontinued operations.
* Capital expenditures :	Capital Expenditures are the cash outflows for long-term productive assets, net of cash from disposals of capital assets.
* Price	: The medium price per share of the company common stock during a given quarter. The prices are as reported, and are not adjusted for subsequent dividends.
* Price high :	The highest price per share of the company common stock during a given quarter.
* Price low	: The lowest price of the company common stock during a quarter.
* ROE	: Return on equity is the ratio of Earnings (available to common stockholders) TTM (over the Trailing Twelve Months) to TTM average common shareholders' equity.
* ROA	: Return on assets is the ratio of total Earnings TTM to TTM average Assets.
* Book value of equity per share :	Common stockholders' equity per share, also known as BVPS.
* P/B ratio	: The ratio of Price to Book value of equity per share as of the previous quarter.
* P/E ratio	: The ratio of Price to EPS diluted TTM as of the previous quarter.
* Cumulative dividends per share :	The aggregate amount of dividends paid per split-adjusted share of common stock from the first available reporting quarter until a given quarter.
* Dividend payout ratio	: The ratio of Dividends TTM to Earnings (available to common stockholders) TTM.
* Long-term debt to equity ratio	: The ratio of Long-term debt to common shareholders' equity (Shareholders equity minus Preferred equity).
* Equity to assets ratio	: The ratio of common shareholders' equity (Shareholders equity minus * Preferred equity) to Assets.
* Current ratio	: The ratio of Current assets to Current liabilities.
* Net margin :	The ratio of Earnings (available for common stockholders) TTM to Revenue TTM.
* Asset turnover :	The ratio of Revenue TTM to TTM average Assets.
* Free cash flow per share	: Cash from operating activities minus the Capital Expenditures for a quarter.


## Tidyquant

This sub-folders contains 10 csv files and are the output of the *MakeFile_Tidyquant.rmd* : 


i. Dividends and StockPrice. csv which contains, on a 


Continue.......

## NewsWeek 


NEWSWEEK	
	
More details : 	http://s.newsweek.com/sites/www.newsweek.com/files/newsweek_green_rankings_final_methodology_2016.pdf

EnergyProductivity 	"In the first step, each company's Energy Productivity is calculated for 2015, with Energy Productivity defined as Revenue ($US) / (Total Energy Consumption (GJ) - Renewable Energy Consumption (GJ)). Each company’s Energy Productivity is then percent-ranked against that of all Industry Group peers in the CK research universe and multiplied by 0.75. The Global Industry Classification Standard (GICS) definition of “Industry Group” is used.

In the second step, the change in each company’s Energy Productivity from 2013-2015 is calculated and percent-ranked against that of all same-Industry Group peers within the CK research universe. If the company’s percent-ranked 2015 Energy Productivity is top quartile, their percent-ranked change in Energy Productivity for 2013-2015 is multiplied by 1 and then by 0.25. If the company’s percent-ranked 2015 Energy Productivity is second quartile, their percent-ranked change in Energy Productivity for 2013-2015 is multiplied by 0.75 and then by 0.25. If the company’s percent-ranked 2015 Energy Productivity is third quartile, their percent-ranked change in Energy Productivity for 2013-2015 is multiplied by 0.5 and then by 0.25. If the company’s percent-ranked 2015 Energy Productivity is bottom quartile, their percent-ranked change in Energy Productivity for 2013-2015 is multiplied by 0.25 and then by 0.25.

In the third step, the values from the first and second steps are totaled."
CarbonProductivity	"In the first step, each company's GHG Productivity is calculated for 2015, with GHG Productivity defined as Revenue ($US) / Total Greenhouse gas (GHG) Emissions (CO2e). Only Scope 1 and Scope 2 emissions are included according to the GHG Protocol. Each company’s GHG Productivity is then percent-ranked against that of all Industry Group peers in the CK research universe and multiplied by 0.75.

In the second step, the change in each company’s GHG Productivity from 2013-2015 is calculated and percent-ranked against that of all same-industry group peers within the CK research universe. If the company’s percent-ranked 2015 GHG Productivity is top quartile, their percent-ranked change in GHG Productivity for 2013-2015 is multiplied by 1 and then by 0.25. If the company’s percent-ranked 2015 GHG Productivity is second quartile, their percent-ranked change in GHG Productivity for 2013-2015 is multiplied by 0.75 and then by 0.25. If the company’s percent-ranked 2015 GHG Productivity is the third quartile, their percent-ranked change in GHG Productivity for 2013-2015 is multiplied by 0.5 and then by 0.25. If the company’s percent-ranked 2015 GHG Productivity is bottom quartile, their percent-ranked change in GHG Productivity for 2013-2015 is multiplied by 0.25 and then by 0.25.

In the third step, the values from the first and second steps are totaled and then multiplied by 0.9.

In the fourth step, if the company disclosed Scope 3 GHG emissions in 2015, a score of 100% is attributed and then multiplied by 0.1. Otherwise, a score of 0% is given.

In the final step, the scores from the third and fourth steps are added."
WaterProductivity	"In the first step, each company's Water Productivity is calculated for 2015. Water Productivity is defined as Revenue ($US) / Total water use (m3). Each company’s Water Productivity is then percent-ranked against that of all Industry Group peers in the CK research universe and multiplied by 0.75.

In the second step, the change in each company’s Water Productivity from 2013-2015 is calculated and percent-ranked against that of all same-industry group peers within the CK research universe. If the company’s percent-ranked 2015 Water Productivity is top quartile, their percent-ranked change in Water Productivity for 2013-2015 is multiplied by 1 and then by 0.25. If the company’s percent-ranked 2015 Water Productivity is second quartile, their percent-ranked change in Water Productivity for 2013-2015 is multiplied by 0.75 and then by 0.25. If the company’s percent-ranked 2015 Water Productivity is the third quartile, their percent-ranked change in Water Productivity for 2013-2015 is multiplied by 0.5 and then by 0.25. If the company’s percent-ranked 2015 Water Productivity is bottom quartile, their percent-ranked change in Water Productivity for 2013-2015 is multiplied by 0.25 and then by 0.25.

In the third step, the values from the first and second steps are totaled."
WasteProductivity	"In the first step, each company's Waste Productivity is calculated for 2015. Waste Productivity is defined as Revenue ($US) / [Total waste generated (metric tonnes) – waste recycled/reused/composted (tonnes)]. Each company’s Waste Productivity is then percent-ranked against that of all Industry Group peers in the CK research universe and multiplied by 0.75.

In the second step, the change in each company’s Waste Productivity from 2013-2015 is calculated and percent-ranked against that of all same-industry group peers within the CK research universe. If the company’s percent-ranked 2015 Waste Productivity is top quartile, their percent-ranked change in Waste Productivity for 2013-2015 is multiplied by 1 and then by 0.25. If the company’s percent-ranked 2015 Waste Productivity is second quartile, their percent-ranked change in Waste Productivity for 2013-2015 is multiplied by 0.75 and then by 0.25. If the company’s percent-ranked 2015 Waste Productivity is third quartile, their percent-ranked change in Waste Productivity for 2013-2015 is multiplied by 0.5 and then by 0.25. If the company’s percent-ranked 2015 Waste Productivity is bottom quartile, their percent-ranked change in Waste Productivity for 2013-2015 is multiplied by 0.25 and then by 0.25.

In the third step, the values from the first and second steps are totaled."
GreenRevenue	In the first step, each company's total revenue for 2015 is broken into its RBICS sub-industry segments as provided by FactSet Data; the percent revenue from each RBICS sub-industry segment is obtained. In the second step, each RBICS sub-industry segment is assigned a green revenue percent based on a taxonomy derived from by (1) Statistics Canada Clean Technology taxonomy, (2) Eurostat, (3) U.S. Bureau of Labor Statistics Green Goods & Services and (4) Climate Bonds Taxonomy. This enables the calculation of a green revenue potential. The annual and sustainability reports of all companies with potential green revenues greater than 10 percent are manually inspected to verify the actual green revenue percent, which then classified in one of five ranges (0-20%, 21-40%, 41-60%, 61-80%, 81-100%).
SustainabilityPayLink	A mechanism to link the remuneration of any member of a company's senior executive team with the achievement of environmental performance targets. The existence of such a link is awarded a score of 100%. A score of 0% is attributed if there is no such mechanism in place.
SustainableThemedCommitment	The existence of a committee at the Board of Directors level whose mandate is related to the sustainability of the company, including but not limited to environmental matters. A score of 100% is awarded if such a committee exists, and a score of 0% is given in cases where such a committee is absent.
AuditScore	The company provides evidence that the latest reported environmental metrics are audited by a third party. A score of 100% is awarded if such an audit has been performed, and a score of 0% is given in cases where such an audit was not performed.
RankNewsWeekGR	Ranking of the companies in the NewsWeek Green Ranking of the year
YearNewsWeekGR	Year of the NewsWeek Green Ranking
GreenScore	The green score of the company which is a weighted average of the eight KPI score





